-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_SCU
-- Unit(s) Under Test: Drv_SCU
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Subprogram: NC_AXI2APB_TZPC_EN

-- Test Case: NC_AXI2APB_TZPC_EN.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_AXI2APB_TZPC_EN
TEST.NEW
TEST.NAME:NC_AXI2APB_TZPC_EN.001
TEST.END

-- Subprogram: NC_InitReset

-- Test Case: NC_InitReset.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_InitReset
TEST.NEW
TEST.NAME:NC_InitReset.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CLKEN.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo[0].tStrap.Bit.mBootMemory:2
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CLKEN.Reg:0x3E3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:0
TEST.END

-- Test Case: NC_InitReset.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_InitReset
TEST.NEW
TEST.NAME:NC_InitReset.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CLKEN.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo[0].tStrap.Bit.mBootMemory:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CLKEN.Reg:0x3E3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:0
TEST.END

-- Test Case: NC_InitReset.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_InitReset
TEST.NEW
TEST.NAME:NC_InitReset.003
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_DMAC0_AXI:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_DMAC1_AXI:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_QSPI_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_QSPI_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo[0].tStrap.Bit.mBootMemory:0
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_DMAC0_AXI:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_DMAC1_AXI:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_QSPI_CORE:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_QSPI_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:0
TEST.END

-- Test Case: NC_InitReset.004
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_InitReset
TEST.NEW
TEST.NAME:NC_InitReset.004
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_UART0_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_UART0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo[0].tStrap.Bit.mBootMemory:4
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_UART0_CORE:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_UART0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:0
TEST.END

-- Test Case: NC_InitReset.005
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_InitReset
TEST.NEW
TEST.NAME:NC_InitReset.005
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:1
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootInfo[0].tStrap.Bit.mBootMemory:3
TEST.VALUE:Drv_SCU.NC_InitReset.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI0_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SYS_CLKEN_1.Bit.CLKEN_PERI1_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_ANALOG_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_ICU:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_0.Bit.ONGO_RST_ACT_BLK_SAFETY:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_1.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_5.Bit.ONGO_RST_ACT_HSP_APB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].ONGO_RST_ACT_7.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AHB_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_AXI_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_CORE_ONGO_RST_ACT.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_RX_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_RX:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_SD_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_TIMER:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_TIMER_ONGO_RST_ACT.Bit.ONGO_RST_ACT_EMMC_CQETIMER:0
TEST.END

-- Subprogram: NC_PMU_BlockPowerON

-- Test Case: NC_PMU_BlockPowerON.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_PMU_BlockPowerON
TEST.NEW
TEST.NAME:NC_PMU_BlockPowerON.001
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:1
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.EXPECTED:Drv_SCU.NC_PMU_BlockPowerON.return:-1
TEST.END

-- Test Case: NC_PMU_BlockPowerON.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_PMU_BlockPowerON
TEST.NEW
TEST.NAME:NC_PMU_BlockPowerON.002
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:0
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:5,11
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0xFFF
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.EXPECTED:Drv_SCU.NC_PMU_BlockPowerON.return:-1
TEST.END

-- Test Case: NC_PMU_BlockPowerON.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_PMU_BlockPowerON
TEST.NEW
TEST.NAME:NC_PMU_BlockPowerON.003
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].SC_STATUS_BLK_USB.Bit.SC_STATUS_BLK_USB:0
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:0
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:5,7
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0xFFF
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.EXPECTED:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.END

-- Test Case: NC_PMU_BlockPowerON.004
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_PMU_BlockPowerON
TEST.NEW
TEST.NAME:NC_PMU_BlockPowerON.004
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].SC_STATUS_BLK_USB.Bit.SC_STATUS_BLK_USB:1
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:0
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:5,7
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].ISO_EN_BLK_USB.Reg:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].PWR_OFF_BLK_USB.Bit.PWR_OFF_BLK_USB:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].T_WAKEUP_DLY_BLK_USB.Bit.T_WAKEUP_DLY_BLK_USB:0xFFF
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_PMU_SCU[0].MANU_EN_BLK_USB.Bit.MANU_EN_BLK_USB:0
TEST.EXPECTED:Drv_SCU.NC_PMU_BlockPowerON.return:0
TEST.END

-- Subprogram: NC_SCU_GetClk

-- Test Case: NC_SCU_GetClk.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetClk
TEST.NEW
TEST.NAME:NC_SCU_GetClk.001
TEST.STUB:Drv_SCU.NC_SCU_GetPLL
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap[0].Reg:2
TEST.VALUE:Drv_SCU.NC_SCU_GetClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetClk.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetClk.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetClk.ptBootStatus[0].ptHandleBoot[0].tStrap.Reg:2
TEST.END

-- Subprogram: NC_SCU_GetMsec

-- Test Case: NC_SCU_GetMsec.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetMsec
TEST.NEW
TEST.NAME:NC_SCU_GetMsec.001
TEST.STUB:Drv_SCU.NC_SCU_GetTick
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.Cls:1
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.return:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:1
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:0
TEST.EXPECTED:Drv_SCU.NC_SCU_GetMsec.Cls:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetMsec.return:0
TEST.END

-- Test Case: NC_SCU_GetMsec.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetMsec
TEST.NEW
TEST.NAME:NC_SCU_GetMsec.002
TEST.STUB:Drv_SCU.NC_SCU_GetTick
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:10000
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.Cls:1
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.return:10000000
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:1
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:10000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetTick.Cls:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetMsec.Cls:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetMsec.return:1000000
TEST.END

-- Subprogram: NC_SCU_GetPLL

-- Test Case: NC_SCU_GetPLL.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetPLL
TEST.NEW
TEST.NAME:NC_SCU_GetPLL.001
TEST.STUB:Drv_SCU.NC_SCU_POR_HoldReset
TEST.STUB:Drv_SCU.NC_SCU_POR_ReleaseReset
TEST.STUB:Drv_SCU.NC_SCU_SetSysClk
TEST.STUB:Drv_SCU.NC_SCU_SetPeriClk
TEST.STUB:Drv_SCU.NC_SCU_SetHSPClk
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:1300000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap[0].Bit.mPLLConfig:1
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:0
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:1000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:1200000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:1300000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:1300000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.END

-- Test Case: NC_SCU_GetPLL.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetPLL
TEST.NEW
TEST.NAME:NC_SCU_GetPLL.002
TEST.STUB:Drv_SCU.NC_SCU_POR_HoldReset
TEST.STUB:Drv_SCU.NC_SCU_POR_ReleaseReset
TEST.STUB:Drv_SCU.NC_SCU_SetSysClk
TEST.STUB:Drv_SCU.NC_SCU_SetPeriClk
TEST.STUB:Drv_SCU.NC_SCU_SetHSPClk
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:2400000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:2600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap[0].Bit.mPLLConfig:2,3
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:0
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:2400000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:2600000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:2400000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:2600000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.END

-- Test Case: NC_SCU_GetPLL.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetPLL
TEST.NEW
TEST.NAME:NC_SCU_GetPLL.003
TEST.STUB:Drv_SCU.NC_SCU_POR_HoldReset
TEST.STUB:Drv_SCU.NC_SCU_POR_ReleaseReset
TEST.STUB:Drv_SCU.NC_SCU_SetSysClk
TEST.STUB:Drv_SCU.NC_SCU_SetPeriClk
TEST.STUB:Drv_SCU.NC_SCU_SetHSPClk
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptStrap[0].Bit.mPLLConfig:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:0
TEST.VALUE:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:0
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mSYS_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mNPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptClock[0].mCOM_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mNPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_GetPLL.ptSCUClk_PLL[0].mCOM_PLL:24000000
TEST.END

-- Subprogram: NC_SCU_GetTick

-- Test Case: NC_SCU_GetTick.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetTick
TEST.NEW
TEST.NAME:NC_SCU_GetTick.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT_CONTROL.Bit.TICK_CNT1_CLEAR:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_L.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_H.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.Cls:1
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT_CONTROL.Bit.TICK_CNT1_CLEAR:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_L.Reg:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_H.Reg:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetTick.Cls:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetTick.return:4294967297
TEST.END

-- Test Case: NC_SCU_GetTick.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_GetTick
TEST.NEW
TEST.NAME:NC_SCU_GetTick.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT_CONTROL.Bit.TICK_CNT1_CLEAR:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_L.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_H.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT_CONTROL.Bit.TICK_CNT1_CLEAR:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_L.Reg:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].TICK_CNT1_H.Reg:1
TEST.EXPECTED:Drv_SCU.NC_SCU_GetTick.Cls:0
TEST.EXPECTED:Drv_SCU.NC_SCU_GetTick.return:4294967297
TEST.END

-- Subprogram: NC_SCU_Initialize

-- Test Case: NC_SCU_Initialize.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_Initialize
TEST.NEW
TEST.NAME:NC_SCU_Initialize.001
TEST.STUB:Drv_SCU.NC_SCU_USB_PowerAndSetClk
TEST.STUB:Drv_SCU.NC_SCU_GetClk
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].STRAP_STATE.Reg:0x10
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tClock.mAPB:40000000
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:uut_prototype_stubs.NC_SetDBG_STRAP_Config.BootStrap:0x10
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:40000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0x10
TEST.END

-- Test Case: NC_SCU_Initialize.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_Initialize
TEST.NEW
TEST.NAME:NC_SCU_Initialize.002
TEST.STUB:Drv_SCU.NC_SCU_USB_PowerAndSetClk
TEST.STUB:Drv_SCU.NC_SCU_GetClk
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].STRAP_STATE.Reg:0x91
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tClock.mAPB:40000000
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:uut_prototype_stubs.NC_SetDBG_STRAP_Config.BootStrap:0x91
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:0x3F
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0x4
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:5
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:40000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0x91
TEST.END

-- Test Case: NC_SCU_Initialize.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_Initialize
TEST.NEW
TEST.NAME:NC_SCU_Initialize.003
TEST.STUB:Drv_SCU.NC_SCU_USB_PowerAndSetClk
TEST.STUB:Drv_SCU.NC_SCU_GetClk
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].STRAP_STATE.Reg:0x11
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Bit.mIncMainBusDiv:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tClock.mAPB:40000000
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:uut_prototype_stubs.NC_SetDBG_STRAP_Config.BootStrap:0x10
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:0x3F
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0x3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:5
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:40000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0x11
TEST.END

-- Test Case: NC_SCU_Initialize.004
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_Initialize
TEST.NEW
TEST.NAME:NC_SCU_Initialize.004
TEST.STUB:Drv_SCU.NC_SCU_USB_PowerAndSetClk
TEST.STUB:Drv_SCU.NC_SCU_GetClk
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].STRAP_STATE.Reg:0x93
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tClock.mAPB:40000000
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:uut_prototype_stubs.NC_SetDBG_STRAP_Config.BootStrap:0x93
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:0x3F
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0x6
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:2
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:40000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0x93
TEST.END

-- Test Case: NC_SCU_Initialize.005
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_Initialize
TEST.NEW
TEST.NAME:NC_SCU_Initialize.005
TEST.STUB:Drv_SCU.NC_SCU_USB_PowerAndSetClk
TEST.STUB:Drv_SCU.NC_SCU_GetClk
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].STRAP_STATE.Reg:0x13
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:1
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tClock.mAPB:40000000
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_Initialize.ptBootStatus[0].ptHandleBoot:<<malloc 1>>
TEST.VALUE:uut_prototype_stubs.NC_SetDBG_STRAP_Config.BootStrap:0x13
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PLL_OUT_CLKMUX.Reg:0x3F
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_BUS_MAIN_CLKDIV.Bit.CLKDIV_VAL_BUS_MAIN:0x5
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:2
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG0.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG1.Reg:40000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_Initialize.ptBootInfo[0].tStrap.Reg:0x13
TEST.END

-- Subprogram: NC_SCU_POR_HoldReset

-- Test Case: NC_SCU_POR_HoldReset.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_HoldReset
TEST.NEW
TEST.NAME:NC_SCU_POR_HoldReset.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_0.Bit.HSP_POR_RST_ACT_0:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_1.Bit.HSP_POR_RST_ACT_1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_2.Bit.HSP_POR_RST_ACT_2:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_0.Bit.HSP_POR_RST_ACT_0:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_1.Bit.HSP_POR_RST_ACT_1:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_2.Bit.HSP_POR_RST_ACT_2:1
TEST.END

-- Test Case: NC_SCU_POR_HoldReset.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_HoldReset
TEST.NEW
TEST.NAME:NC_SCU_POR_HoldReset.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PUL_RST_ACT_6.Bit.PUL_RST_ACT_BLK_USB_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_0.Bit.USB_POR_RST_ACT_0:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_1.Bit.USB_POR_RST_ACT_1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_2.Bit.USB_POR_RST_ACT_2:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PUL_RST_ACT_6.Bit.PUL_RST_ACT_BLK_USB_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_0.Bit.USB_POR_RST_ACT_0:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_1.Bit.USB_POR_RST_ACT_1:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_2.Bit.USB_POR_RST_ACT_2:1
TEST.END

-- Test Case: NC_SCU_POR_HoldReset.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_HoldReset
TEST.NEW
TEST.NAME:NC_SCU_POR_HoldReset.003
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:2
TEST.END

-- Subprogram: NC_SCU_POR_ReleaseReset

-- Test Case: NC_SCU_POR_ReleaseReset.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_ReleaseReset
TEST.NEW
TEST.NAME:NC_SCU_POR_ReleaseReset.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_0.Bit.HSP_POR_RST_ACT_0:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_1.Bit.HSP_POR_RST_ACT_1:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_2.Bit.HSP_POR_RST_ACT_2:1
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_0.Bit.HSP_POR_RST_ACT_0:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_1.Bit.HSP_POR_RST_ACT_1:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].HSP_POR_RST_ACT_2.Bit.HSP_POR_RST_ACT_2:0
TEST.END

-- Test Case: NC_SCU_POR_ReleaseReset.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_ReleaseReset
TEST.NEW
TEST.NAME:NC_SCU_POR_ReleaseReset.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PUL_RST_ACT_6.Bit.PUL_RST_ACT_BLK_USB_APB:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_0.Bit.USB_POR_RST_ACT_0:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_1.Bit.USB_POR_RST_ACT_1:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_2.Bit.USB_POR_RST_ACT_2:1
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PUL_RST_ACT_6.Bit.PUL_RST_ACT_BLK_USB_APB:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_0.Bit.USB_POR_RST_ACT_0:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_1.Bit.USB_POR_RST_ACT_1:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].USB_POR_RST_ACT_2.Bit.USB_POR_RST_ACT_2:0
TEST.END

-- Test Case: NC_SCU_POR_ReleaseReset.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_POR_ReleaseReset
TEST.NEW
TEST.NAME:NC_SCU_POR_ReleaseReset.003
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:3
TEST.END

-- Subprogram: NC_SCU_SetHSPClk

-- Test Case: NC_SCU_SetHSPClk.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetHSPClk
TEST.NEW
TEST.NAME:NC_SCU_SetHSPClk.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CORE_CLKDIV.Bit.CLKDIV_VAL_SD_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_IO_CLKDIV.Bit.CLKDIV_VAL_SD_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CORE_CLKDIV.Bit.CLKDIV_VAL_EMMC_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_IO_CLKDIV.Bit.CLKDIV_VAL_EMMC_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_PRE_CLKMUX.Bit.CLKMUX_SEL_HSP_PRE2:1
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:150000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:150000000
TEST.END

-- Test Case: NC_SCU_SetHSPClk.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetHSPClk
TEST.NEW
TEST.NAME:NC_SCU_SetHSPClk.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CORE_CLKDIV.Bit.CLKDIV_VAL_SD_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_IO_CLKDIV.Bit.CLKDIV_VAL_SD_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CORE_CLKDIV.Bit.CLKDIV_VAL_EMMC_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_IO_CLKDIV.Bit.CLKDIV_VAL_EMMC_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_PRE_CLKMUX.Bit.CLKMUX_SEL_HSP_PRE2:2
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:200000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:200000000
TEST.END

-- Test Case: NC_SCU_SetHSPClk.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetHSPClk
TEST.NEW
TEST.NAME:NC_SCU_SetHSPClk.003
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CORE_CLKDIV.Bit.CLKDIV_VAL_SD_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_IO_CLKDIV.Bit.CLKDIV_VAL_SD_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CORE_CLKDIV.Bit.CLKDIV_VAL_EMMC_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_IO_CLKDIV.Bit.CLKDIV_VAL_EMMC_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_PRE_CLKMUX.Bit.CLKMUX_SEL_HSP_PRE2:3
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:250000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:250000000
TEST.END

-- Test Case: NC_SCU_SetHSPClk.004
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetHSPClk
TEST.NEW
TEST.NAME:NC_SCU_SetHSPClk.004
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_CORE_CLKDIV.Bit.CLKDIV_VAL_SD_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].SD_IO_CLKDIV.Bit.CLKDIV_VAL_SD_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_CORE_CLKDIV.Bit.CLKDIV_VAL_EMMC_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].EMMC_IO_CLKDIV.Bit.CLKDIV_VAL_EMMC_IO:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_HSP_SCU[0].HSP_PRE_CLKMUX.Bit.CLKMUX_SEL_HSP_PRE2:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:0
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_SetHSPClk.ptSCUClk_PLL[0].mCOM_PLL:2000000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mSD:125000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetHSPClk.ptClock[0].mEMMC:125000000
TEST.END

-- Subprogram: NC_SCU_SetPeriClk

-- Test Case: NC_SCU_SetPeriClk.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetPeriClk
TEST.NEW
TEST.NAME:NC_SCU_SetPeriClk.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SEC_PRE1_CLKMUX.Bit.CLKMUX_SEL_SEC_PRE1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PERI_PRE2_CLKMUX.Bit.CLKMUX_SEL_PERI_PRE2:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].QSPI_PRE1_CLKMUX.Bit.CLKMUX_SEL_QSPI_PRE1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_CMRT_CLKDIV.Bit.CLKDIV_VAL_CMRT:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_QSPI_CORE_CLKDIV.Bit.CLKDIV_VAL_QSPI_CORE:2
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSPI:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mQSPI:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mUART:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCMRT:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SEC_PRE1_CLKMUX.Bit.CLKMUX_SEL_SEC_PRE1:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PERI_PRE2_CLKMUX.Bit.CLKMUX_SEL_PERI_PRE2:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].QSPI_PRE1_CLKMUX.Bit.CLKMUX_SEL_QSPI_PRE1:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_CMRT_CLKDIV.Bit.CLKDIV_VAL_CMRT:2
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:2
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_QSPI_CORE_CLKDIV.Bit.CLKDIV_VAL_QSPI_CORE:2
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSPI:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mQSPI:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mUART:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCMRT:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.END

-- Test Case: NC_SCU_SetPeriClk.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetPeriClk
TEST.NEW
TEST.NAME:NC_SCU_SetPeriClk.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SEC_PRE1_CLKMUX.Bit.CLKMUX_SEL_SEC_PRE1:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PERI_PRE2_CLKMUX.Bit.CLKMUX_SEL_PERI_PRE2:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].QSPI_PRE1_CLKMUX.Bit.CLKMUX_SEL_QSPI_PRE1:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_CMRT_CLKDIV.Bit.CLKDIV_VAL_CMRT:3
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:3
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_QSPI_CORE_CLKDIV.Bit.CLKDIV_VAL_QSPI_CORE:3
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSPI:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mQSPI:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mUART:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCMRT:0
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.VALUE:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].SEC_PRE1_CLKMUX.Bit.CLKMUX_SEL_SEC_PRE1:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].PERI_PRE2_CLKMUX.Bit.CLKMUX_SEL_PERI_PRE2:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].QSPI_PRE1_CLKMUX.Bit.CLKMUX_SEL_QSPI_PRE1:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_CMRT_CLKDIV.Bit.CLKDIV_VAL_CMRT:3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_UART_CORE_CLKDIV.Bit.CLKDIV_VAL_UART_CORE:3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_QSPI_CORE_CLKDIV.Bit.CLKDIV_VAL_QSPI_CORE:3
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mSPI:8000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mQSPI:8000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mUART:8000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptClock[0].mCMRT:8000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetPeriClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.END

-- Subprogram: NC_SCU_SetSysClk

-- Test Case: NC_SCU_SetSysClk.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetSysClk
TEST.NEW
TEST.NAME:NC_SCU_SetSysClk.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_PRE2_CLKMUX.Bit.CLKMUX_SEL_BUS_PRE2:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_SYS_APB_CLKDIV.Bit.CLKDIV_VAL_SYS_APB:2
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mAPB:0
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_PRE2_CLKMUX.Bit.CLKMUX_SEL_BUS_PRE2:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_SYS_APB_CLKDIV.Bit.CLKDIV_VAL_SYS_APB:2
TEST.EXPECTED:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mAPB:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mSYS_PLL:24000000
TEST.END

-- Test Case: NC_SCU_SetSysClk.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_SetSysClk
TEST.NEW
TEST.NAME:NC_SCU_SetSysClk.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_PRE2_CLKMUX.Bit.CLKMUX_SEL_BUS_PRE2:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_SYS_APB_CLKDIV.Bit.CLKDIV_VAL_SYS_APB:2
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mAPB:0
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_PRE2_CLKMUX.Bit.CLKMUX_SEL_BUS_PRE2:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].VAL_SYS_APB_CLKDIV.Bit.CLKDIV_VAL_SYS_APB:2
TEST.EXPECTED:Drv_SCU.NC_SCU_SetSysClk.ptClock[0].mAPB:12000000
TEST.EXPECTED:Drv_SCU.NC_SCU_SetSysClk.ptSCUClk_PLL[0].mCPU_PLL:24000000
TEST.END

-- Subprogram: NC_SCU_StrapConfig

-- Test Case: NC_SCU_StrapConfig.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_StrapConfig
TEST.NEW
TEST.NAME:NC_SCU_StrapConfig.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG15.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tImage.mCLK_INV:0
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tStrap.Bit.mBootMemory:3
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG15.Reg:3
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.EXPECTED:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tImage.mCLK_INV:1
TEST.EXPECTED:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tStrap.Bit.mBootMemory:0
TEST.END

-- Test Case: NC_SCU_StrapConfig.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_StrapConfig
TEST.NEW
TEST.NAME:NC_SCU_StrapConfig.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG15.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tImage.mCLK_INV:0
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tStrap.Bit.mBootMemory:5
TEST.VALUE:Drv_SCU.NC_SCU_StrapConfig.ptBootStatus:<<malloc 1>>
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG15.Reg:5
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_StrapConfig.ptBootInfo[0].tImage.mCLK_INV:0
TEST.END

-- Subprogram: NC_SCU_USB_EnableClock

-- Test Case: NC_SCU_USB_EnableClock.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_USB_EnableClock
TEST.NEW
TEST.NAME:NC_SCU_USB_EnableClock.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USBC_BUS:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_SUSPEND:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_REF_CLK:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_EnableClock.iOnOff:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USBC_BUS:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_SUSPEND:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_REF_CLK:1
TEST.END

-- Test Case: NC_SCU_USB_EnableClock.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_USB_EnableClock
TEST.NEW
TEST.NAME:NC_SCU_USB_EnableClock.002
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USBC_BUS:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_SUSPEND:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_REF_CLK:1
TEST.VALUE:Drv_SCU.NC_SCU_USB_EnableClock.iOnOff:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USBC_BUS:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_SUSPEND:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_CLKEN.Bit.CLKEN_USB_REF_CLK:0
TEST.END

-- Subprogram: NC_SCU_USB_PowerAndSetClk

-- Test Case: NC_SCU_USB_PowerAndSetClk.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_USB_PowerAndSetClk
TEST.NEW
TEST.NAME:NC_SCU_USB_PowerAndSetClk.001
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo[0].tStrap.Bit.mBootMemory:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock:<<malloc 1>>
TEST.END

-- Test Case: NC_SCU_USB_PowerAndSetClk.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_USB_PowerAndSetClk
TEST.NEW
TEST.NAME:NC_SCU_USB_PowerAndSetClk.002
TEST.STUB:Drv_SCU.NC_SCU_USB_EnableClock
TEST.STUB:Drv_SCU.NC_PMU_BlockPowerON
TEST.STUB:Drv_SCU.NC_SCU_POR_HoldReset
TEST.STUB:Drv_SCU.NC_SCU_POR_ReleaseReset
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_PRE1_CLKMUX.Bit.CLKMUX_SEL_USB_PRE1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_PRE2_CLKMUX.Bit.CLKMUX_SEL_USB_PRE2:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USBC_BUS.Bit.CLKDIV_VAL_USBC_BUS:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USB_SUSPEND.Bit.CLKDIV_VAL_USB_SUSPEND:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USB_REF.Bit.CLKDIV_VAL_USB_REF_CLK:2
TEST.VALUE:Drv_SCU.NC_SCU_USB_EnableClock.iOnOff:1
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:1
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:1
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo[0].tStrap.Bit.mBootMemory:5
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_SUSPEND:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_REF_CLK:0
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB:250000000
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_SUSPEND:600000000
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_REF_CLK:600000000
TEST.END

-- Test Case: NC_SCU_USB_PowerAndSetClk.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_USB_PowerAndSetClk
TEST.NEW
TEST.NAME:NC_SCU_USB_PowerAndSetClk.003
TEST.STUB:Drv_SCU.NC_SCU_USB_EnableClock
TEST.STUB:Drv_SCU.NC_PMU_BlockPowerON
TEST.STUB:Drv_SCU.NC_SCU_POR_HoldReset
TEST.STUB:Drv_SCU.NC_SCU_POR_ReleaseReset
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_PRE1_CLKMUX.Bit.CLKMUX_SEL_USB_PRE1:1
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].USB_PRE2_CLKMUX.Bit.CLKMUX_SEL_USB_PRE2:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USBC_BUS.Bit.CLKDIV_VAL_USBC_BUS:4
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USB_SUSPEND.Bit.CLKDIV_VAL_USB_SUSPEND:2
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_USB_SCU[0].VAL_USB_REF.Bit.CLKDIV_VAL_USB_REF_CLK:2
TEST.VALUE:Drv_SCU.NC_SCU_USB_EnableClock.iOnOff:1
TEST.VALUE:Drv_SCU.NC_PMU_BlockPowerON.BlkID:0
TEST.VALUE:Drv_SCU.NC_SCU_POR_HoldReset.BlkID:1
TEST.VALUE:Drv_SCU.NC_SCU_POR_ReleaseReset.BlkID:1
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptBootInfo[0].tStrap.Bit.mBootMemory:5
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock:<<malloc 1>>
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mSYS_PLL:1000000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mCPU_PLL:1200000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mNPU_PLL:1600000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mCOM_PLL:2000000000
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_SUSPEND:0
TEST.VALUE:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_REF_CLK:0
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB:300000000
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_SUSPEND:500000000
TEST.EXPECTED:Drv_SCU.NC_SCU_USB_PowerAndSetClk.ptClock[0].mUSB_REF_CLK:500000000
TEST.END

-- Subprogram: NC_SCU_WaitTick

-- Test Case: NC_SCU_WaitTick.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_WaitTick
TEST.NEW
TEST.NAME:NC_SCU_WaitTick.001
TEST.STUB:Drv_SCU.NC_SCU_GetTick
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetTick.return:VARY FROM:1 TO:11 BY: 1
TEST.VALUE:Drv_SCU.NC_SCU_WaitTick.Ticks:10
TEST.END

-- Subprogram: NC_SCU_mTimeOut

-- Test Case: NC_SCU_mTimeOut.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_mTimeOut
TEST.NEW
TEST.NAME:NC_SCU_mTimeOut.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.mSec:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.END

-- Test Case: NC_SCU_mTimeOut.002
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_mTimeOut
TEST.NEW
TEST.NAME:NC_SCU_mTimeOut.002
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:0x10000000A
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0x14
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0x1
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.END

-- Test Case: NC_SCU_mTimeOut.003
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_mTimeOut
TEST.NEW
TEST.NAME:NC_SCU_mTimeOut.003
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:10
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:10
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:10
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:10
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:10
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.END

-- Test Case: NC_SCU_mTimeOut.004
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SCU_mTimeOut
TEST.NEW
TEST.NAME:NC_SCU_mTimeOut.004
TEST.STUB:Drv_SCU.NC_SCU_GetMsec
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:10
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:10
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.Cls:0
TEST.VALUE:Drv_SCU.NC_SCU_GetMsec.return:0xA00000014
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.VALUE:Drv_SCU.NC_SCU_mTimeOut.return:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG2.Reg:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].DEBUG3.Reg:0
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.mSec:10
TEST.EXPECTED:Drv_SCU.NC_SCU_mTimeOut.return:1
TEST.END

-- Subprogram: NC_SYS_SCU_TZPROT_EN

-- Test Case: NC_SYS_SCU_TZPROT_EN.001
TEST.UNIT:Drv_SCU
TEST.SUBPROGRAM:NC_SYS_SCU_TZPROT_EN
TEST.NEW
TEST.NAME:NC_SYS_SCU_TZPROT_EN.001
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU:<<malloc 1>>
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_0:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_1:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_2:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_3:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_4:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_5:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_7:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_8:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_9:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_10:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_11:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_12:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_13:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_14:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_15:0
TEST.VALUE:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_16:0
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_0:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_1:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_2:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_3:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_4:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_5:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_6:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_7:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_8:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_9:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_10:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_11:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_12:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_13:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_14:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_15:1
TEST.EXPECTED:Drv_SCU.<<GLOBAL>>.RegA6_SYS_SCU[0].BUS_S_TZPROT.Bit.BUS_S_TZPROT_16:1
TEST.END
