-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_UART
-- Unit(s) Under Test: Drv_Uart
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: Drv_Uart

-- Subprogram: NC_UART_GetCharN

-- Test Case: NC_UART_GetCharN.001
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_GetCharN
TEST.NEW
TEST.NAME:NC_UART_GetCharN.001
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Bit.RBR_DLL_THR:0x31
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_STAT.Reg:0x1
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.c:<<malloc 1>>
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.c[0]:0x0
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.return:0
TEST.EXPECTED:Drv_Uart.NC_UART_GetCharN.c[0]:0x31
TEST.EXPECTED:Drv_Uart.NC_UART_GetCharN.return:0
TEST.END

-- Test Case: NC_UART_GetCharN.002
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_GetCharN
TEST.NEW
TEST.NAME:NC_UART_GetCharN.002
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Bit.RBR_DLL_THR:0x31
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_STAT.Reg:0x0
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.c:<<malloc 1>>
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.c[0]:0x0
TEST.VALUE:Drv_Uart.NC_UART_GetCharN.return:0
TEST.EXPECTED:Drv_Uart.NC_UART_GetCharN.c[0]:0x0
TEST.EXPECTED:Drv_Uart.NC_UART_GetCharN.return:-1
TEST.END

-- Subprogram: NC_UART_GetLineStat

-- Test Case: NC_UART_GetLineStat.001
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_GetLineStat
TEST.NEW
TEST.NAME:NC_UART_GetLineStat.001
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_STAT.Reg:1
TEST.VALUE:Drv_Uart.NC_UART_GetLineStat.return:0
TEST.EXPECTED:Drv_Uart.NC_UART_GetLineStat.return:1
TEST.END

-- Subprogram: NC_UART_Initialize

-- Test Case: NC_UART_Initialize.001
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_Initialize
TEST.NEW
TEST.NAME:NC_UART_Initialize.001
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_DLH_IER.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_FCR_IIR.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_CTRL.Reg:0
TEST.VALUE:Drv_Uart.NC_UART_Initialize.BaudRate:115200
TEST.VALUE:Drv_Uart.NC_UART_Initialize.RefClk:40000000
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:0x15
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_DLH_IER.Reg:0x15
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_FCR_IIR.Reg:0x17
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_CTRL.Reg:0x3
TEST.END

-- Test Case: NC_UART_Initialize.002
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_Initialize
TEST.NEW
TEST.NAME:NC_UART_Initialize.002
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_DLH_IER.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_FCR_IIR.Reg:0
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_CTRL.Reg:0
TEST.VALUE:Drv_Uart.NC_UART_Initialize.BaudRate:230400
TEST.VALUE:Drv_Uart.NC_UART_Initialize.RefClk:40000000
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:0xB
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_DLH_IER.Reg:0x15
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_FCR_IIR.Reg:0x17
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_LINE_CTRL.Reg:0x3
TEST.END

-- Subprogram: NC_UART_PutChar

-- Test Case: NC_UART_PutChar.001
TEST.UNIT:Drv_Uart
TEST.SUBPROGRAM:NC_UART_PutChar
TEST.NEW
TEST.NAME:NC_UART_PutChar.001
TEST.STUB:Drv_Uart.NC_UART_GetLineStat
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART:<<malloc 1>>
TEST.VALUE:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:0
TEST.VALUE:Drv_Uart.NC_UART_GetLineStat.return:2,32,1,96
TEST.VALUE:Drv_Uart.NC_UART_PutChar.Data:'2'
TEST.EXPECTED:Drv_Uart.<<GLOBAL>>.RegA6_UART[0].UART_RBR_DLL_THR.Reg:50
TEST.END
