-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_EMMC
-- Unit(s) Under Test: Drv_EMMC
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Subprogram: NC_EMMC_CheckCMDLineWork

-- Test Case: NC_EMMC_CheckCMDLineWork.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckCMDLineWork
TEST.NEW
TEST.NAME:NC_EMMC_CheckCMDLineWork.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_CMD:0
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckCMDLineWork.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckCMDLineWork.return:1
TEST.END

-- Test Case: NC_EMMC_CheckCMDLineWork.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckCMDLineWork
TEST.NEW
TEST.NAME:NC_EMMC_CheckCMDLineWork.002
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_CMD:1
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckCMDLineWork.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckCMDLineWork.return:0
TEST.END

-- Subprogram: NC_EMMC_CheckClkStable

-- Test Case: NC_EMMC_CheckClkStable.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckClkStable
TEST.NEW
TEST.NAME:NC_EMMC_CheckClkStable.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Bit.INTERNAL_CLK_STABLE:1
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckClkStable.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckClkStable.return:1
TEST.END

-- Test Case: NC_EMMC_CheckClkStable.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckClkStable
TEST.NEW
TEST.NAME:NC_EMMC_CheckClkStable.002
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Bit.INTERNAL_CLK_STABLE:0
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckClkStable.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckClkStable.return:0
TEST.END

-- Subprogram: NC_EMMC_CheckDATLineWork

-- Test Case: NC_EMMC_CheckDATLineWork.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckDATLineWork
TEST.NEW
TEST.NAME:NC_EMMC_CheckDATLineWork.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_DAT:0
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckDATLineWork.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckDATLineWork.return:1
TEST.END

-- Test Case: NC_EMMC_CheckDATLineWork.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_CheckDATLineWork
TEST.NEW
TEST.NAME:NC_EMMC_CheckDATLineWork.002
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_DAT:1
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckDATLineWork.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_CheckDATLineWork.return:0
TEST.END

-- Subprogram: NC_EMMC_DeInit

-- Test Case: NC_EMMC_DeInit.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_DeInit
TEST.NEW
TEST.NAME:NC_EMMC_DeInit.001
TEST.STUB:Drv_EMMC.NC_EMMC_ResetDevice
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:0
TEST.END

-- Subprogram: NC_EMMC_EnableMultiBlkSelect

-- Test Case: NC_EMMC_EnableMultiBlkSelect.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_EnableMultiBlkSelect
TEST.NEW
TEST.NAME:NC_EMMC_EnableMultiBlkSelect.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:1
TEST.VALUE:Drv_EMMC.NC_EMMC_EnableMultiBlkSelect.blockCount:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.END

-- Test Case: NC_EMMC_EnableMultiBlkSelect.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_EnableMultiBlkSelect
TEST.NEW
TEST.NAME:NC_EMMC_EnableMultiBlkSelect.002
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.VALUE:Drv_EMMC.NC_EMMC_EnableMultiBlkSelect.blockCount:2
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:1
TEST.END

-- Subprogram: NC_EMMC_GetFreqDiv

-- Test Case: NC_EMMC_GetFreqDiv.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_EMMC_GetFreqDiv.001
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.ref_freq:10
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.freq:10
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_GetFreqDiv.return:0
TEST.END

-- Test Case: NC_EMMC_GetFreqDiv.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_EMMC_GetFreqDiv.002
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.ref_freq:2046
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.freq:0
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_GetFreqDiv.return:1023
TEST.END

-- Test Case: NC_EMMC_GetFreqDiv.003
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_EMMC_GetFreqDiv.003
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.ref_freq:10
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.freq:1
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_GetFreqDiv.return:3
TEST.END

-- Subprogram: NC_EMMC_Initialize

-- Test Case: NC_EMMC_Initialize.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_Initialize
TEST.NEW
TEST.NAME:NC_EMMC_Initialize.001
TEST.STUB:Drv_EMMC.NC_EMMC_GetFreqDiv
TEST.STUB:Drv_EMMC.NC_EMMC_SetClock
TEST.STUB:Drv_EMMC.NC_EMMC_ResetDevice
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.DAT_XFER_WIDTH:1
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.DMA_SEL:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.EXT_DAT_XFER:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].PWR_CTRL_R.Bit.SD_BUS_PWR_VDD1:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].PWR_CTRL_R.Bit.SD_BUS_VOL_VDD1:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].TOUT_CTRL_R.Bit.TOUT_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.CMD_COMPLETE_STAT_EN:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.XFER_COMPLETE_STAT_EN:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.DMA_INTERRUPT_STAT_EN:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.BUF_RD_READY_STAT_EN:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_SIGNAL_EN_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.UHS_MODE_SEL:1
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.UHS2_IF_ENABLE:1
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.ADMA2_LEN_MODE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.HOST_VER4_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.ADDRESSING:1
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.CARD_IS_EMMC:0
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.ref_freq:40000000
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.freq:25000000
TEST.VALUE:Drv_EMMC.NC_EMMC_GetFreqDiv.return:40000
TEST.VALUE:Drv_EMMC.NC_EMMC_SetClock.freq_sel:40000
TEST.VALUE:Drv_EMMC.NC_EMMC_Initialize.RefClk:40000000
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.DAT_XFER_WIDTH:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.DMA_SEL:2
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL1_R.Bit.EXT_DAT_XFER:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].PWR_CTRL_R.Bit.SD_BUS_PWR_VDD1:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].PWR_CTRL_R.Bit.SD_BUS_VOL_VDD1:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].TOUT_CTRL_R.Bit.TOUT_CNT:0xE
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_R.Reg:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.CMD_COMPLETE_STAT_EN:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.XFER_COMPLETE_STAT_EN:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.DMA_INTERRUPT_STAT_EN:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_EN_R.Bit.BUF_RD_READY_STAT_EN:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_STAT_EN_R.Reg:0xFFFF
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_SIGNAL_EN_R.Reg:0xFFFF
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.UHS_MODE_SEL:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.UHS2_IF_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.ADMA2_LEN_MODE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.HOST_VER4_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].HOST_CTRL2_R.Bit.ADDRESSING:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.CARD_IS_EMMC:1
TEST.END

-- Subprogram: NC_EMMC_IntrADMAErr

-- Test Case: NC_EMMC_IntrADMAErr.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_IntrADMAErr
TEST.NEW
TEST.NAME:NC_EMMC_IntrADMAErr.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_STAT_R.Bit.ADMA_ERR:1
TEST.VALUE:Drv_EMMC.NC_EMMC_IntrADMAErr.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_IntrADMAErr.return:1
TEST.END

-- Test Case: NC_EMMC_IntrADMAErr.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_IntrADMAErr
TEST.NEW
TEST.NAME:NC_EMMC_IntrADMAErr.002
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ERROR_INT_STAT_R.Bit.ADMA_ERR:0
TEST.VALUE:Drv_EMMC.NC_EMMC_IntrADMAErr.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_IntrADMAErr.return:0
TEST.END

-- Subprogram: NC_EMMC_PrepareADMA2Descriptor

-- Test Case: NC_EMMC_PrepareADMA2Descriptor.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_PrepareADMA2Descriptor
TEST.NEW
TEST.NAME:NC_EMMC_PrepareADMA2Descriptor.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ADMA_SA_LOW_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ADMA_SA_HIGH_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:0
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].ADMA_SA_HIGH_R.Reg:0
TEST.END

-- Test Case: NC_EMMC_PrepareADMA2Descriptor.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_PrepareADMA2Descriptor
TEST.NEW
TEST.NAME:NC_EMMC_PrepareADMA2Descriptor.002
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:0x10
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:10
TEST.END

-- Test Case: NC_EMMC_PrepareADMA2Descriptor.003
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_PrepareADMA2Descriptor
TEST.NEW
TEST.NAME:NC_EMMC_PrepareADMA2Descriptor.003
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:0x3
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.buffer:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.buffer[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:512
TEST.VALUE:uut_prototype_stubs.NC_Get_Firmware_Backup_Offset.return:0
TEST.END

-- Subprogram: NC_EMMC_Read2DummyBuffer

-- Test Case: NC_EMMC_Read2DummyBuffer.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_Read2DummyBuffer
TEST.NEW
TEST.NAME:NC_EMMC_Read2DummyBuffer.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BUF_DATA_R.Reg:20
TEST.VALUE:Drv_EMMC.NC_EMMC_Read2DummyBuffer.count:10
TEST.END

-- Subprogram: NC_EMMC_ReadByADMA2

-- Test Case: NC_EMMC_ReadByADMA2.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByADMA2
TEST.NEW
TEST.NAME:NC_EMMC_ReadByADMA2.001
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.buffer:"1"
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:512
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.Size:512
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.return:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByADMA2.return:0
TEST.END

-- Test Case: NC_EMMC_ReadByADMA2.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByADMA2
TEST.NEW
TEST.NAME:NC_EMMC_ReadByADMA2.002
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_IntrADMAErr
TEST.STUB:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:-1
TEST.VALUE:Drv_EMMC.NC_EMMC_IntrADMAErr.return:1
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.buffer:"1"
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:512
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.Size:513
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.return:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:2
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByADMA2.return:-1
TEST.END

-- Test Case: NC_EMMC_ReadByADMA2.003
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByADMA2
TEST.NEW
TEST.NAME:NC_EMMC_ReadByADMA2.003
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_IntrADMAErr
TEST.STUB:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:-1
TEST.VALUE:Drv_EMMC.NC_EMMC_IntrADMAErr.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.buffer:"1"
TEST.VALUE:Drv_EMMC.NC_EMMC_PrepareADMA2Descriptor.Size:512
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.rtype:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.Size:513
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByADMA2.return:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:2
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.MULTI_BLK_SEL:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByADMA2.return:-1
TEST.END

-- Subprogram: NC_EMMC_ReadByFIFO

-- Test Case: NC_EMMC_ReadByFIFO.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByFIFO
TEST.NEW
TEST.NAME:NC_EMMC_ReadByFIFO.001
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:32,2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:-1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:10
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.rtype:1
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.Size:8
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.END

-- Test Case: NC_EMMC_ReadByFIFO.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByFIFO
TEST.NEW
TEST.NAME:NC_EMMC_ReadByFIFO.002
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BUF_DATA_R.Reg:0x12345678
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:32,2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:4
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.rtype:1
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.Size:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0x12345678
TEST.END

-- Test Case: NC_EMMC_ReadByFIFO.003
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByFIFO
TEST.NEW
TEST.NAME:NC_EMMC_ReadByFIFO.003
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BUF_DATA_R.Reg:0x12345678
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:32,2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:4
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:10
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.rtype:2
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.Size:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0x0
TEST.END

-- Test Case: NC_EMMC_ReadByFIFO.004
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByFIFO
TEST.NEW
TEST.NAME:NC_EMMC_ReadByFIFO.004
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BUF_DATA_R.Reg:0x12345678
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:32,2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:4
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.rtype:2
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.Size:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0x12345678
TEST.END

-- Test Case: NC_EMMC_ReadByFIFO.005
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ReadByFIFO
TEST.NEW
TEST.NAME:NC_EMMC_ReadByFIFO.005
TEST.STUB:Drv_EMMC.NC_EMMC_Wait_INT
TEST.STUB:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BUF_DATA_R.Reg:0x12345678
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:32,2
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:4
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.rtype:3
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_ReadByFIFO.Size:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SDMASA_R.Reg:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.XFER_BLOCK_SIZE:512
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKSIZE_R.Bit.SDMA_BUF_BDARY:7
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BLOCKCOUNT_R.Bit.BLOCK_CNT:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DMA_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.BLOCK_COUNT_ENABLE:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.AUTO_CMD_ENABLE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].XFER_MODE_R.Bit.DATA_XFER_DIR:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].BOOT_CTRL_R.Reg:0x81
TEST.EXPECTED:Drv_EMMC.NC_EMMC_ReadByFIFO.pData[0]:0x12345678
TEST.END

-- Subprogram: NC_EMMC_ResetDevice

-- Test Case: NC_EMMC_ResetDevice.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_ResetDevice
TEST.NEW
TEST.NAME:NC_EMMC_ResetDevice.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_ALL:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.EMMC_RST_N:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.EMMC_RST_N_OE:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Bit.SW_RST_ALL:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.EMMC_RST_N:1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].EMMC_CTRL_R.Bit.EMMC_RST_N_OE:1
TEST.END

-- Subprogram: NC_EMMC_SetClock

-- Test Case: NC_EMMC_SetClock.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_SetClock
TEST.NEW
TEST.NAME:NC_EMMC_SetClock.001
TEST.STUB:Drv_EMMC.NC_EMMC_waitForClockStatble
TEST.STUB:Drv_EMMC.NC_EMMC_waitForCMDLineWork
TEST.STUB:Drv_EMMC.NC_EMMC_waitForDATLineWork
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForClockStatble.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForCMDLineWork.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForDATLineWork.return:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetClock.freq_sel:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetClock.return:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:0x10D
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].SW_RST_R.Reg:0x4
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetClock.return:0
TEST.END

-- Test Case: NC_EMMC_SetClock.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_SetClock
TEST.NEW
TEST.NAME:NC_EMMC_SetClock.002
TEST.STUB:Drv_EMMC.NC_EMMC_waitForClockStatble
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:0
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForClockStatble.return:-1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetClock.freq_sel:2
TEST.VALUE:Drv_EMMC.NC_EMMC_SetClock.return:0
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].CLK_CTRL_R.Reg:0x201
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetClock.return:-1
TEST.END

-- Subprogram: NC_EMMC_SetSkipSizeAndBlkCount

-- Test Case: NC_EMMC_SetSkipSizeAndBlkCount.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_SetSkipSizeAndBlkCount
TEST.NEW
TEST.NAME:NC_EMMC_SetSkipSizeAndBlkCount.001
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:1
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:16
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.END

-- Test Case: NC_EMMC_SetSkipSizeAndBlkCount.002
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_SetSkipSizeAndBlkCount
TEST.NEW
TEST.NAME:NC_EMMC_SetSkipSizeAndBlkCount.002
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:2
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.VALUE:uut_prototype_stubs.NC_Get_Firmware_Backup_Offset.return:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:16
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:640
TEST.END

-- Test Case: NC_EMMC_SetSkipSizeAndBlkCount.003
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_SetSkipSizeAndBlkCount
TEST.NEW
TEST.NAME:NC_EMMC_SetSkipSizeAndBlkCount.003
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.readType:3
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:0
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount:<<malloc 1>>
TEST.VALUE:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipCount[0]:0
TEST.EXPECTED:Drv_EMMC.NC_EMMC_SetSkipSizeAndBlkCount.pSkipBlkCount[0]:0
TEST.END

-- Subprogram: NC_EMMC_Wait_INT

-- Test Case: NC_EMMC_Wait_INT.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_Wait_INT
TEST.NEW
TEST.NAME:NC_EMMC_Wait_INT.001
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC:<<malloc 1>>
TEST.VALUE:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_R.Reg:0x0,0xF
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.Value:0xFFFF
TEST.VALUE:Drv_EMMC.NC_EMMC_Wait_INT.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_EMMC.<<GLOBAL>>.RegA6_EMMC[0].NORMAL_INT_STAT_R.Reg:0xFFFF
TEST.EXPECTED:Drv_EMMC.NC_EMMC_Wait_INT.return:-1,0
TEST.END

-- Subprogram: NC_EMMC_waitForCMDLineWork

-- Test Case: NC_EMMC_waitForCMDLineWork.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_waitForCMDLineWork
TEST.NEW
TEST.NAME:NC_EMMC_waitForCMDLineWork.001
TEST.STUB:Drv_EMMC.NC_EMMC_CheckCMDLineWork
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckCMDLineWork.return:0,1
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForCMDLineWork.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_EMMC.NC_EMMC_waitForCMDLineWork.return:-1
TEST.END

-- Subprogram: NC_EMMC_waitForClockStatble

-- Test Case: NC_EMMC_waitForClockStatble.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_waitForClockStatble
TEST.NEW
TEST.NAME:NC_EMMC_waitForClockStatble.001
TEST.STUB:Drv_EMMC.NC_EMMC_CheckClkStable
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckClkStable.return:0,1
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForClockStatble.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_EMMC.NC_EMMC_waitForClockStatble.return:-1
TEST.END

-- Subprogram: NC_EMMC_waitForDATLineWork

-- Test Case: NC_EMMC_waitForDATLineWork.001
TEST.UNIT:Drv_EMMC
TEST.SUBPROGRAM:NC_EMMC_waitForDATLineWork
TEST.NEW
TEST.NAME:NC_EMMC_waitForDATLineWork.001
TEST.STUB:Drv_EMMC.NC_EMMC_CheckDATLineWork
TEST.VALUE:Drv_EMMC.NC_EMMC_CheckDATLineWork.return:0,1
TEST.VALUE:Drv_EMMC.NC_EMMC_waitForDATLineWork.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_EMMC.NC_EMMC_waitForDATLineWork.return:-1
TEST.END
