-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_SDC
-- Unit(s) Under Test: Drv_SDC
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Subprogram: NC_SDC_ACMD41

-- Test Case: NC_SDC_ACMD41.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_ACMD41
TEST.NEW
TEST.NAME:NC_SDC_ACMD41.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD41.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0x40FF8000
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x2902
TEST.EXPECTED:Drv_SDC.NC_SDC_ACMD41.return:1
TEST.END

-- Subprogram: NC_SDC_ACMD6

-- Test Case: NC_SDC_ACMD6.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_ACMD6
TEST.NEW
TEST.NAME:NC_SDC_ACMD6.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD6.Argument:20
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:20
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x61A
TEST.END

-- Subprogram: NC_SDC_CMD0

-- Test Case: NC_SDC_CMD0.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD0
TEST.NEW
TEST.NAME:NC_SDC_CMD0.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:1
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x22
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.END

-- Subprogram: NC_SDC_CMD16

-- Test Case: NC_SDC_CMD16.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD16
TEST.NEW
TEST.NAME:NC_SDC_CMD16.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD16.Argument:5
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:5
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x101A
TEST.END

-- Subprogram: NC_SDC_CMD17

-- Test Case: NC_SDC_CMD17.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD17
TEST.NEW
TEST.NAME:NC_SDC_CMD17.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD_DAT
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].BLOCKSIZE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].BLOCKCOUNT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].BUF_DATA_R.Reg:0x2
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1,32,2
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD_DAT.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.Argument:20
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData:<<malloc 5>>
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[0]:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[1]:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[2]:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[3]:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[4]:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].BLOCKSIZE_R.Reg:512
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].BLOCKCOUNT_R.Reg:1
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:20
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x16
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x113A
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD17.pData[0]:2
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD17.pData[1]:2
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD17.pData[2]:2
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD17.pData[3]:2
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD17.pData[4]:2
TEST.END

-- Subprogram: NC_SDC_CMD2

-- Test Case: NC_SDC_CMD2.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD2
TEST.NEW
TEST.NAME:NC_SDC_CMD2.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:1
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x22
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x209
TEST.END

-- Subprogram: NC_SDC_CMD3

-- Test Case: NC_SDC_CMD3.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD3
TEST.NEW
TEST.NAME:NC_SDC_CMD3.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:1
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:0xFF0000
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:0
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x31A
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:0xFF0000
TEST.END

-- Subprogram: NC_SDC_CMD55

-- Test Case: NC_SDC_CMD55.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD55
TEST.NEW
TEST.NAME:NC_SDC_CMD55.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.Argument:32
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD55.return:1
TEST.END

-- Subprogram: NC_SDC_CMD7

-- Test Case: NC_SDC_CMD7.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD7
TEST.NEW
TEST.NAME:NC_SDC_CMD7.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1,2
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD7.Argument:1
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:1
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x71B
TEST.END

-- Subprogram: NC_SDC_CMD8

-- Test Case: NC_SDC_CMD8.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD8
TEST.NEW
TEST.NAME:NC_SDC_CMD8.001
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:0x100
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0x1AA
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x81A
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD8.return:0
TEST.END

-- Test Case: NC_SDC_CMD8.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD8
TEST.NEW
TEST.NAME:NC_SDC_CMD8.002
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:0x10
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0x1AA
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x81A
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD8.return:-1
TEST.END

-- Test Case: NC_SDC_CMD8.003
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CMD8
TEST.NEW
TEST.NAME:NC_SDC_CMD8.003
TEST.STUB:Drv_SDC.SD_Wait_INT
TEST.STUB:Drv_SDC.SD_WaitCMD
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].RESP01_R.Reg:0x200
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ARGUMENT_R.Reg:0x1AA
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].XFER_MODE_R.Reg:0x32
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CMD_R.Reg:0x81A
TEST.EXPECTED:Drv_SDC.NC_SDC_CMD8.return:-1
TEST.END

-- Subprogram: NC_SDC_CheckCMDLineWork

-- Test Case: NC_SDC_CheckCMDLineWork.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckCMDLineWork
TEST.NEW
TEST.NAME:NC_SDC_CheckCMDLineWork.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Bit.SW_RST_CMD:0
TEST.VALUE:Drv_SDC.NC_SDC_CheckCMDLineWork.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckCMDLineWork.return:1
TEST.END

-- Test Case: NC_SDC_CheckCMDLineWork.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckCMDLineWork
TEST.NEW
TEST.NAME:NC_SDC_CheckCMDLineWork.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Bit.SW_RST_CMD:1
TEST.VALUE:Drv_SDC.NC_SDC_CheckCMDLineWork.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckCMDLineWork.return:0
TEST.END

-- Subprogram: NC_SDC_CheckClkStable

-- Test Case: NC_SDC_CheckClkStable.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckClkStable
TEST.NEW
TEST.NAME:NC_SDC_CheckClkStable.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Bit.INTERNAL_CLK_STABLE:1
TEST.VALUE:Drv_SDC.NC_SDC_CheckClkStable.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckClkStable.return:1
TEST.END

-- Test Case: NC_SDC_CheckClkStable.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckClkStable
TEST.NEW
TEST.NAME:NC_SDC_CheckClkStable.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Bit.INTERNAL_CLK_STABLE:0
TEST.VALUE:Drv_SDC.NC_SDC_CheckClkStable.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckClkStable.return:0
TEST.END

-- Subprogram: NC_SDC_CheckDATLineWork

-- Test Case: NC_SDC_CheckDATLineWork.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckDATLineWork
TEST.NEW
TEST.NAME:NC_SDC_CheckDATLineWork.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Bit.SW_RST_DAT:0
TEST.VALUE:Drv_SDC.NC_SDC_CheckDATLineWork.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckDATLineWork.return:1
TEST.END

-- Test Case: NC_SDC_CheckDATLineWork.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_CheckDATLineWork
TEST.NEW
TEST.NAME:NC_SDC_CheckDATLineWork.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Bit.SW_RST_DAT:1
TEST.VALUE:Drv_SDC.NC_SDC_CheckDATLineWork.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_CheckDATLineWork.return:0
TEST.END

-- Subprogram: NC_SDC_DeInit

-- Test Case: NC_SDC_DeInit.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_DeInit
TEST.NEW
TEST.NAME:NC_SDC_DeInit.001
TEST.STUB:Drv_SDC.NC_SDC_CMD0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:1
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:0
TEST.END

-- Subprogram: NC_SDC_GetFreqDiv

-- Test Case: NC_SDC_GetFreqDiv.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_SDC_GetFreqDiv.001
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:0
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:1
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_GetFreqDiv.return:0
TEST.END

-- Test Case: NC_SDC_GetFreqDiv.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_SDC_GetFreqDiv.002
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:10
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:1
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_GetFreqDiv.return:3
TEST.END

-- Test Case: NC_SDC_GetFreqDiv.003
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_GetFreqDiv
TEST.NEW
TEST.NAME:NC_SDC_GetFreqDiv.003
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:2046
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:0
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:0
TEST.EXPECTED:Drv_SDC.NC_SDC_GetFreqDiv.return:1023
TEST.END

-- Subprogram: NC_SDC_Init

-- Test Case: NC_SDC_Init.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_Init
TEST.NEW
TEST.NAME:NC_SDC_Init.001
TEST.STUB:Drv_SDC.NC_SDC_GetFreqDiv
TEST.STUB:Drv_SDC.NC_SDC_SetClock
TEST.STUB:Drv_SDC.NC_SDC_CMD0
TEST.STUB:Drv_SDC.NC_SDC_CMD8
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:40000000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:400000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.freq_sel:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:-1
TEST.VALUE:Drv_SDC.NC_SDC_Init.RefClk:40000000
TEST.VALUE:Drv_SDC.NC_SDC_Init.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:2
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0xF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0xE
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0xFF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0xFFF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0x5C00
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0x11
TEST.EXPECTED:Drv_SDC.NC_SDC_Init.return:-1
TEST.END

-- Test Case: NC_SDC_Init.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_Init
TEST.NEW
TEST.NAME:NC_SDC_Init.002
TEST.STUB:Drv_SDC.NC_SDC_GetFreqDiv
TEST.STUB:Drv_SDC.NC_SDC_SetClock
TEST.STUB:Drv_SDC.NC_SDC_CMD0
TEST.STUB:Drv_SDC.NC_SDC_CMD8
TEST.STUB:Drv_SDC.NC_SDC_CMD55
TEST.STUB:Drv_SDC.NC_SDC_ACMD41
TEST.STUB:Drv_SDC.NC_SDC_CMD2
TEST.STUB:Drv_SDC.NC_SDC_CMD3
TEST.STUB:Drv_SDC.NC_SDC_CMD7
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:10
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:40000000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:400000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.freq_sel:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.Argument:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD41.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD7.Argument:10
TEST.VALUE:Drv_SDC.NC_SDC_Init.RefClk:40000000
TEST.VALUE:Drv_SDC.NC_SDC_Init.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:2
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0xF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0xE
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0xFF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0xFFF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0x5C00
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0x11
TEST.EXPECTED:Drv_SDC.NC_SDC_Init.return:0
TEST.END

-- Test Case: NC_SDC_Init.003
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_Init
TEST.NEW
TEST.NAME:NC_SDC_Init.003
TEST.STUB:Drv_SDC.NC_SDC_GetFreqDiv
TEST.STUB:Drv_SDC.NC_SDC_SetClock
TEST.STUB:Drv_SDC.NC_SDC_CMD0
TEST.STUB:Drv_SDC.NC_SDC_CMD8
TEST.STUB:Drv_SDC.NC_SDC_CMD55
TEST.STUB:Drv_SDC.NC_SDC_ACMD41
TEST.STUB:Drv_SDC.NC_SDC_CMD2
TEST.STUB:Drv_SDC.NC_SDC_CMD3
TEST.STUB:Drv_SDC.NC_SDC_CMD7
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:10
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.ref_freq:40000000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.freq:400000
TEST.VALUE:Drv_SDC.NC_SDC_GetFreqDiv.return:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.freq_sel:40000
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.return:-1
TEST.VALUE:Drv_SDC.NC_SDC_CMD8.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.Argument:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD41.return:0
TEST.VALUE:Drv_SDC.NC_SDC_CMD7.Argument:10
TEST.VALUE:Drv_SDC.NC_SDC_Init.RefClk:40000000
TEST.VALUE:Drv_SDC.NC_SDC_Init.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL1_R.Reg:2
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PWR_CTRL_R.Reg:0xF
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].TOUT_CTRL_R.Reg:0x0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_EN_R.Reg:0x0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].ERROR_INT_STAT_EN_R.Reg:0x0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].HOST_CTRL2_R.Reg:0x5C00
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].MSHC_CTRL_R.Reg:0x11
TEST.EXPECTED:Drv_SDC.NC_SDC_Init.return:-1
TEST.END

-- Subprogram: NC_SDC_Read

-- Test Case: NC_SDC_Read.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_Read
TEST.NEW
TEST.NAME:NC_SDC_Read.001
TEST.STUB:Drv_SDC.NC_SDC_CMD55
TEST.STUB:Drv_SDC.NC_SDC_ACMD6
TEST.STUB:Drv_SDC.NC_SDC_CMD16
TEST.STUB:Drv_SDC.NC_SDC_CMD17
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:200
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.Argument:200
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD6.Argument:2
TEST.VALUE:Drv_SDC.NC_SDC_CMD16.Argument:512
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.Argument:0x10000000
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[0]:0
TEST.VALUE:Drv_SDC.NC_SDC_Read.Addr:0x10000000
TEST.VALUE:Drv_SDC.NC_SDC_Read.pData:<<malloc 1>>
TEST.VALUE:Drv_SDC.NC_SDC_Read.pData[0]:0
TEST.VALUE:Drv_SDC.NC_SDC_Read.Size:512
TEST.END

-- Test Case: NC_SDC_Read.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_Read
TEST.NEW
TEST.NAME:NC_SDC_Read.002
TEST.STUB:Drv_SDC.NC_SDC_CMD55
TEST.STUB:Drv_SDC.NC_SDC_ACMD6
TEST.STUB:Drv_SDC.NC_SDC_CMD16
TEST.STUB:Drv_SDC.NC_SDC_CMD17
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG10.Reg:200
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.Argument:200
TEST.VALUE:Drv_SDC.NC_SDC_CMD55.return:0
TEST.VALUE:Drv_SDC.NC_SDC_ACMD6.Argument:2
TEST.VALUE:Drv_SDC.NC_SDC_CMD16.Argument:512
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.Argument:0x10000000
TEST.VALUE:Drv_SDC.NC_SDC_CMD17.pData[0]:0
TEST.VALUE:Drv_SDC.NC_SDC_Read.Addr:0x10000000
TEST.VALUE:Drv_SDC.NC_SDC_Read.pData:<<malloc 1>>
TEST.VALUE:Drv_SDC.NC_SDC_Read.pData[0]:0
TEST.VALUE:Drv_SDC.NC_SDC_Read.Size:513
TEST.END

-- Subprogram: NC_SDC_SetClock

-- Test Case: NC_SDC_SetClock.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_SetClock
TEST.NEW
TEST.NAME:NC_SDC_SetClock.001
TEST.STUB:Drv_SDC.NC_SDC_waitForClockStatble
TEST.STUB:Drv_SDC.NC_SDC_waitForCMDLineWork
TEST.STUB:Drv_SDC.NC_SDC_waitForDATLineWork
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Reg:0
TEST.VALUE:Drv_SDC.NC_SDC_waitForClockStatble.return:0
TEST.VALUE:Drv_SDC.NC_SDC_waitForCMDLineWork.return:0
TEST.VALUE:Drv_SDC.NC_SDC_waitForDATLineWork.return:0
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.freq_sel:1
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:0x10D
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Reg:4
TEST.EXPECTED:Drv_SDC.NC_SDC_SetClock.return:0
TEST.END

-- Test Case: NC_SDC_SetClock.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_SetClock
TEST.NEW
TEST.NAME:NC_SDC_SetClock.002
TEST.STUB:Drv_SDC.NC_SDC_waitForClockStatble
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:0
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Reg:0
TEST.VALUE:Drv_SDC.NC_SDC_waitForClockStatble.return:-1
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.freq_sel:1
TEST.VALUE:Drv_SDC.NC_SDC_SetClock.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].CLK_CTRL_R.Reg:0x101
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].SW_RST_R.Reg:0
TEST.EXPECTED:Drv_SDC.NC_SDC_SetClock.return:-1
TEST.END

-- Subprogram: NC_SDC_waitForCMDLineWork

-- Test Case: NC_SDC_waitForCMDLineWork.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_waitForCMDLineWork
TEST.NEW
TEST.NAME:NC_SDC_waitForCMDLineWork.001
TEST.STUB:Drv_SDC.NC_SDC_CheckCMDLineWork
TEST.VALUE:Drv_SDC.NC_SDC_CheckCMDLineWork.return:0,1
TEST.VALUE:Drv_SDC.NC_SDC_waitForCMDLineWork.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.NC_SDC_waitForCMDLineWork.return:-1
TEST.END

-- Subprogram: NC_SDC_waitForClockStatble

-- Test Case: NC_SDC_waitForClockStatble.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_waitForClockStatble
TEST.NEW
TEST.NAME:NC_SDC_waitForClockStatble.001
TEST.STUB:Drv_SDC.NC_SDC_CheckClkStable
TEST.VALUE:Drv_SDC.NC_SDC_CheckClkStable.return:0,1
TEST.VALUE:Drv_SDC.NC_SDC_waitForClockStatble.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.NC_SDC_waitForClockStatble.return:-1
TEST.END

-- Subprogram: NC_SDC_waitForDATLineWork

-- Test Case: NC_SDC_waitForDATLineWork.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:NC_SDC_waitForDATLineWork
TEST.NEW
TEST.NAME:NC_SDC_waitForDATLineWork.001
TEST.STUB:Drv_SDC.NC_SDC_CheckDATLineWork
TEST.VALUE:Drv_SDC.NC_SDC_CheckDATLineWork.return:0,1
TEST.VALUE:Drv_SDC.NC_SDC_waitForDATLineWork.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.NC_SDC_waitForDATLineWork.return:-1
TEST.END

-- Subprogram: SD_WaitCMD

-- Test Case: SD_WaitCMD.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_WaitCMD
TEST.NEW
TEST.NAME:SD_WaitCMD.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PSTATE_REG.Bit.CMD_INHIBIT:0
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0
TEST.EXPECTED:Drv_SDC.SD_WaitCMD.return:0
TEST.END

-- Test Case: SD_WaitCMD.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_WaitCMD
TEST.NEW
TEST.NAME:SD_WaitCMD.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PSTATE_REG.Bit.CMD_INHIBIT:1
TEST.VALUE:Drv_SDC.SD_WaitCMD.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.SD_WaitCMD.return:-1
TEST.END

-- Subprogram: SD_WaitCMD_DAT

-- Test Case: SD_WaitCMD_DAT.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_WaitCMD_DAT
TEST.NEW
TEST.NAME:SD_WaitCMD_DAT.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PSTATE_REG.Bit.CMD_INHIBIT_DAT:0
TEST.VALUE:Drv_SDC.SD_WaitCMD_DAT.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0
TEST.EXPECTED:Drv_SDC.SD_WaitCMD_DAT.return:0
TEST.END

-- Test Case: SD_WaitCMD_DAT.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_WaitCMD_DAT
TEST.NEW
TEST.NAME:SD_WaitCMD_DAT.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].PSTATE_REG.Bit.CMD_INHIBIT_DAT:1
TEST.VALUE:Drv_SDC.SD_WaitCMD_DAT.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.SD_WaitCMD_DAT.return:-1
TEST.END

-- Subprogram: SD_Wait_INT

-- Test Case: SD_Wait_INT.001
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_Wait_INT
TEST.NEW
TEST.NAME:SD_Wait_INT.001
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_R.Reg:1
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:3
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_R.Reg:3
TEST.EXPECTED:Drv_SDC.SD_Wait_INT.return:0
TEST.END

-- Test Case: SD_Wait_INT.002
TEST.UNIT:Drv_SDC
TEST.SUBPROGRAM:SD_Wait_INT
TEST.NEW
TEST.NAME:SD_Wait_INT.002
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD:<<malloc 1>>
TEST.VALUE:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_R.Reg:4
TEST.VALUE:Drv_SDC.SD_Wait_INT.Value:3
TEST.VALUE:Drv_SDC.SD_Wait_INT.return:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.EXPECTED:Drv_SDC.<<GLOBAL>>.RegA6_SD[0].NORMAL_INT_STAT_R.Reg:3
TEST.EXPECTED:Drv_SDC.SD_Wait_INT.return:-1
TEST.END
