-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_LD
-- Unit(s) Under Test: load_IMG
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Test Case: NC_LD_JumpImage.001
TEST.UNIT:load_IMG
TEST.SUBPROGRAM:NC_LD_JumpImage
TEST.NEW
TEST.NAME:NC_LD_JumpImage.001
TEST.VALUE:load_IMG.NC_LD_JumpImage.ptBootInfo:<<malloc 1>>
TEST.VALUE:load_IMG.NC_LD_JumpImage.ptBootStatus:<<malloc 1>>
TEST.VALUE:load_IMG.NC_LD_JumpImage.ptBootStatus[0].mBootDone_Res:1,0
TEST.EXPECTED:load_IMG.NC_LD_JumpImage.ptBootStatus[0].mBootDone_Res:1,0
TEST.END
