-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_SPI
-- Unit(s) Under Test: Drv_DMA330 Drv_SPI Svc_sFlash
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: Drv_DMA330

-- Subprogram: NC_DMA_Deinit

-- Test Case: NC_DMA_Deinit.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Deinit
TEST.NEW
TEST.NAME:NC_DMA_Deinit.001
TEST.STUB:Drv_DMA330.NC_DMA_Kill
TEST.VALUE:Drv_DMA330.NC_DMA_Kill.Ch:1
TEST.END

-- Subprogram: NC_DMA_Gen_microCode

-- Test Case: NC_DMA_Gen_microCode.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.001
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:1024
TEST.END

-- Test Case: NC_DMA_Gen_microCode.002
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.002
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:4
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:1024
TEST.END

-- Test Case: NC_DMA_Gen_microCode.003
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.003
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:65536
TEST.END

-- Test Case: NC_DMA_Gen_microCode.004
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.004
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:7
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:65536
TEST.END

-- Test Case: NC_DMA_Gen_microCode.005
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.005
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:7
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:65536
TEST.END

-- Test Case: NC_DMA_Gen_microCode.006
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.006
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:6
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:65536
TEST.END

-- Test Case: NC_DMA_Gen_microCode.007
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Gen_microCode
TEST.NEW
TEST.NAME:NC_DMA_Gen_microCode.007
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.Mode:1
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstSize:17
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcBurstLength:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstSize:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstBurstLength:8
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.EndianSwapSize:0
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.SrcAddress:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.DstAddress:0x21000000
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.PeriNumber:2
TEST.VALUE:Drv_DMA330.NC_DMA_Gen_microCode.Inst.TotalLength:65536
TEST.END

-- Subprogram: NC_DMA_Kill

-- Test Case: NC_DMA_Kill.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Kill
TEST.NEW
TEST.NAME:NC_DMA_Kill.001
TEST.VALUE:Drv_DMA330.NC_DMA_Kill.Ch:1
TEST.END

-- Subprogram: NC_DMA_QSPI_Gen_Instruction

-- Test Case: NC_DMA_QSPI_Gen_Instruction.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_QSPI_Gen_Instruction
TEST.NEW
TEST.NAME:NC_DMA_QSPI_Gen_Instruction.001
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData:<<malloc 3>>
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData[0]:0
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData[1]:1
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData[2]:2
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.Length:3
TEST.END

-- Test Case: NC_DMA_QSPI_Gen_Instruction.002
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_QSPI_Gen_Instruction
TEST.NEW
TEST.NAME:NC_DMA_QSPI_Gen_Instruction.002
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData:<<malloc 9>>
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData:<<null>>
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.Length:3
TEST.END

-- Subprogram: NC_DMA_Run

-- Test Case: NC_DMA_Run.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Run
TEST.NEW
TEST.NAME:NC_DMA_Run.001
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330:<<malloc 1>>
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGCMD.Reg:0
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGINST0.Reg:0
TEST.VALUE:Drv_DMA330.NC_DMA_Run.Ch:1
TEST.EXPECTED:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGCMD.Reg:0
TEST.EXPECTED:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGINST0.Reg:0x1A00000
TEST.END

-- Test Case: NC_DMA_Run.002
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Run
TEST.NEW
TEST.NAME:NC_DMA_Run.002
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330:<<malloc 1>>
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGCMD.Reg:0
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGINST0.Reg:0
TEST.VALUE:Drv_DMA330.NC_DMA_Run.Ch:0
TEST.EXPECTED:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGCMD.Reg:0
TEST.EXPECTED:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGINST0.Reg:0x0
TEST.END

-- Subprogram: NC_DMA_SPI_Gen_Instruction

-- Test Case: NC_DMA_SPI_Gen_Instruction.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_SPI_Gen_Instruction
TEST.NEW
TEST.NAME:NC_DMA_SPI_Gen_Instruction.001
TEST.STUB:Drv_DMA330.NC_DMA_Gen_microCode
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData:<<malloc 3>>
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData[0]:1
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData[1]:2
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData[2]:3
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.Length:3
TEST.END

-- Test Case: NC_DMA_SPI_Gen_Instruction.002
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_SPI_Gen_Instruction
TEST.NEW
TEST.NAME:NC_DMA_SPI_Gen_Instruction.002
TEST.STUB:Drv_DMA330.NC_DMA_Gen_microCode
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData:<<malloc 9>>
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData:<<null>>
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.Length:3
TEST.END

-- Subprogram: NC_DMA_Start

-- Test Case: NC_DMA_Start.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Start
TEST.NEW
TEST.NAME:NC_DMA_Start.001
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330:<<malloc 1>>
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DBGSTATUS.Reg:1
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:6000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.END

-- Subprogram: NC_DMA_Wait_Ch_Complete

-- Test Case: NC_DMA_Wait_Ch_Complete.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Wait_Ch_Complete
TEST.NEW
TEST.NAME:NC_DMA_Wait_Ch_Complete.001
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330:<<malloc 1>>
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DMA330_THR_ST[0].CSR.Bit.CHANNEL_STATUS:0xF
TEST.VALUE:Drv_DMA330.NC_DMA_Wait_Ch_Complete.Ch:0
TEST.END

-- Test Case: NC_DMA_Wait_Ch_Complete.002
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Wait_Ch_Complete
TEST.NEW
TEST.NAME:NC_DMA_Wait_Ch_Complete.002
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330:<<malloc 1>>
TEST.VALUE:Drv_DMA330.<<GLOBAL>>.RegA6_DMA330[0].DMA330_THR_ST[0].CSR.Bit.CHANNEL_STATUS:1
TEST.VALUE:Drv_DMA330.NC_DMA_Wait_Ch_Complete.Ch:0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:500
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.END

-- Subprogram: NC_DMA_Wait_Complete

-- Test Case: NC_DMA_Wait_Complete.001
TEST.UNIT:Drv_DMA330
TEST.SUBPROGRAM:NC_DMA_Wait_Complete
TEST.NEW
TEST.NAME:NC_DMA_Wait_Complete.001
TEST.STUB:Drv_DMA330.NC_DMA_Wait_Ch_Complete
TEST.VALUE:Drv_DMA330.NC_DMA_Wait_Ch_Complete.Ch:1
TEST.END

-- Unit: Drv_SPI

-- Subprogram: NC_QSPI_Init

-- Test Case: NC_QSPI_Init.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Init
TEST.NEW
TEST.NAME:NC_QSPI_Init.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:0
TEST.VALUE:Drv_SPI.NC_QSPI_Init.BitRate:20000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.RefClk:40000000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.DummyCycle:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x477600
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:256
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:2000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0x3219
TEST.END

-- Test Case: NC_QSPI_Init.002
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Init
TEST.NEW
TEST.NAME:NC_QSPI_Init.002
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:1
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_QSPI_Init.BitRate:20000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.RefClk:40000000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.DummyCycle:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x477640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:256
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:2000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0x2219
TEST.END

-- Test Case: NC_QSPI_Init.003
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Init
TEST.NEW
TEST.NAME:NC_QSPI_Init.003
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_QSPI_Init.BitRate:20000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.RefClk:40000000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.DummyCycle:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x477640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:256
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:2000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0x2219
TEST.END

-- Test Case: NC_QSPI_Init.004
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Init
TEST.NEW
TEST.NAME:NC_QSPI_Init.004
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:3
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_QSPI_Init.BitRate:20000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.RefClk:40000000
TEST.VALUE:Drv_SPI.NC_QSPI_Init.DummyCycle:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x477640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:256
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:2000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_QSPI[0].SPI_CTRLR0.Reg:0x2219
TEST.END

-- Subprogram: NC_QSPI_Read

-- Test Case: NC_QSPI_Read.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Read
TEST.NEW
TEST.NAME:NC_QSPI_Read.001
TEST.STUB:Drv_SPI.NC_SPI_WaitBusIsBusy
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x10
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.VALUE:Drv_SPI.NC_QSPI_Read.Length:1
TEST.END

-- Subprogram: NC_QSPI_SetBitRate

-- Test Case: NC_QSPI_SetBitRate.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_SetBitRate
TEST.NEW
TEST.NAME:NC_QSPI_SetBitRate.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Bit.SCKDV:0
TEST.VALUE:Drv_SPI.NC_QSPI_SetBitRate.Div:4
TEST.VALUE:Drv_SPI.NC_QSPI_SetBitRate.RefClk:40000000
TEST.VALUE:Drv_SPI.NC_QSPI_SetBitRate.return:10000000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Bit.SCKDV:4
TEST.EXPECTED:Drv_SPI.NC_QSPI_SetBitRate.return:10000000
TEST.END

-- Subprogram: NC_QSPI_Write

-- Test Case: NC_QSPI_Write.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_QSPI_Write
TEST.NEW
TEST.NAME:NC_QSPI_Write.001
TEST.STUB:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty
TEST.STUB:Drv_SPI.NC_SPI_WaitBusIsBusy
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty.return:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[0]:0x10
TEST.VALUE:Drv_SPI.NC_QSPI_Write.Length:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x10
TEST.END

-- Subprogram: NC_SPI_DeInit

-- Test Case: NC_SPI_DeInit.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_DeInit
TEST.NEW
TEST.NAME:NC_SPI_DeInit.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.END

-- Subprogram: NC_SPI_DisableCS

-- Test Case: NC_SPI_DisableCS.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_DisableCS
TEST.NEW
TEST.NAME:NC_SPI_DisableCS.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_VAL:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_VAL:1
TEST.END

-- Subprogram: NC_SPI_DisableDMAReq

-- Test Case: NC_SPI_DisableDMAReq.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_DisableDMAReq
TEST.NEW
TEST.NAME:NC_SPI_DisableDMAReq.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.RDMAE:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.TDMAE:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.RDMAE:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.TDMAE:0
TEST.END

-- Subprogram: NC_SPI_EnableCS

-- Test Case: NC_SPI_EnableCS.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_EnableCS
TEST.NEW
TEST.NAME:NC_SPI_EnableCS.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_VAL:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_VAL:0
TEST.END

-- Subprogram: NC_SPI_EnableDMAReq

-- Test Case: NC_SPI_EnableDMAReq.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_EnableDMAReq
TEST.NEW
TEST.NAME:NC_SPI_EnableDMAReq.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.RDMAE:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.TDMAE:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.RDMAE:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMACR.Bit.TDMAE:1
TEST.END

-- Subprogram: NC_SPI_Init

-- Test Case: NC_SPI_Init.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Init
TEST.NEW
TEST.NAME:NC_SPI_Init.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_Init.BitRate:200000
TEST.VALUE:Drv_SPI.NC_SPI_Init.RefClk:40000000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x77600
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:200
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.END

-- Test Case: NC_SPI_Init.002
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Init
TEST.NEW
TEST.NAME:NC_SPI_Init.002
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:1
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_SPI_Init.BitRate:200000
TEST.VALUE:Drv_SPI.NC_SPI_Init.RefClk:40000000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x77640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:200
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.END

-- Test Case: NC_SPI_Init.003
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Init
TEST.NEW
TEST.NAME:NC_SPI_Init.003
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_SPI_Init.BitRate:200000
TEST.VALUE:Drv_SPI.NC_SPI_Init.RefClk:40000000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x77640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:200
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.END

-- Test Case: NC_SPI_Init.004
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Init
TEST.NEW
TEST.NAME:NC_SPI_Init.004
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG11.Reg:2
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG12.Reg:3
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG17.Reg:1
TEST.VALUE:Drv_SPI.NC_SPI_Init.BitRate:200000
TEST.VALUE:Drv_SPI.NC_SPI_Init.RefClk:40000000
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Reg:0x77640
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].BAUDR.Reg:200
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].TXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RXFTLR.Reg:0xFF
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMATDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].RX_SAMPLE_DLY.Bit.RSD:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CSN_CONTROL.Bit.CSN_SEL:1
TEST.END

-- Subprogram: NC_SPI_Read

-- Test Case: NC_SPI_Read.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Read
TEST.NEW
TEST.NAME:NC_SPI_Read.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[0]:0x0
TEST.VALUE:Drv_SPI.NC_SPI_Read.Length:1
TEST.ATTRIBUTES:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:EXPECTED_BASE=16
TEST.ATTRIBUTES:Drv_SPI.NC_SPI_Read.pBuf[0]:EXPECTED_BASE=16
TEST.END

-- Subprogram: NC_SPI_SetBitRate

-- Test Case: NC_SPI_SetBitRate.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetBitRate
TEST.NEW
TEST.NAME:NC_SPI_SetBitRate.001
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.pBitRate:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.pBitRate[0]:2000000
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.RefClk:40000000
TEST.END

-- Test Case: NC_SPI_SetBitRate.002
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetBitRate
TEST.NEW
TEST.NAME:NC_SPI_SetBitRate.002
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.pBitRate:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.pBitRate[0]:20000000
TEST.VALUE:Drv_SPI.NC_SPI_SetBitRate.RefClk:400000040
TEST.END

-- Subprogram: NC_SPI_SetDataLevel

-- Test Case: NC_SPI_SetDataLevel.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetDataLevel
TEST.NEW
TEST.NAME:NC_SPI_SetDataLevel.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_SetDataLevel.Rx:3
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DMARDLR.Reg:2
TEST.END

-- Subprogram: NC_SPI_SetFrameSize

-- Test Case: NC_SPI_SetFrameSize.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetFrameSize
TEST.NEW
TEST.NAME:NC_SPI_SetFrameSize.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Bit.DFS_32:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_SetFrameSize.Size:8
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Bit.DFS_32:8
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.END

-- Subprogram: NC_SPI_SetTMOD

-- Test Case: NC_SPI_SetTMOD.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetTMOD
TEST.NEW
TEST.NAME:NC_SPI_SetTMOD.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Bit.TMOD:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR0.Bit.TMOD:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.END

-- Subprogram: NC_SPI_SetTransferLength

-- Test Case: NC_SPI_SetTransferLength.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_SetTransferLength
TEST.NEW
TEST.NAME:NC_SPI_SetTransferLength.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_SetTransferLength.Size:8
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].CTRLR1.Reg:7
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SSIENR.Reg:1
TEST.END

-- Subprogram: NC_SPI_WaitBusIsBusy

-- Test Case: NC_SPI_WaitBusIsBusy.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_WaitBusIsBusy
TEST.NEW
TEST.NAME:NC_SPI_WaitBusIsBusy.001
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:500,0
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SR.Bit.BUSY:1
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.EXPECTED:Drv_SPI.NC_SPI_WaitBusIsBusy.return:-1
TEST.END

-- Subprogram: NC_SPI_WaitTxFIFOIsEmpty

-- Test Case: NC_SPI_WaitTxFIFOIsEmpty.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_WaitTxFIFOIsEmpty
TEST.NEW
TEST.NAME:NC_SPI_WaitTxFIFOIsEmpty.001
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SR.Bit.TFE:1
TEST.END

-- Test Case: NC_SPI_WaitTxFIFOIsEmpty.002
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_WaitTxFIFOIsEmpty
TEST.NEW
TEST.NAME:NC_SPI_WaitTxFIFOIsEmpty.002
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SR.Bit.TFE:0
TEST.END

-- Subprogram: NC_SPI_Write

-- Test Case: NC_SPI_Write.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Write
TEST.NEW
TEST.NAME:NC_SPI_Write.001
TEST.STUB:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty
TEST.STUB:Drv_SPI.NC_SPI_WaitBusIsBusy
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty.return:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x10
TEST.END

-- Subprogram: NC_SPI_Write32

-- Test Case: NC_SPI_Write32.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_Write32
TEST.NEW
TEST.NAME:NC_SPI_Write32.001
TEST.STUB:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty
TEST.STUB:Drv_SPI.NC_SPI_WaitBusIsBusy
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:0
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty.return:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.VALUE:Drv_SPI.NC_SPI_Write32.pBuf:<<malloc 1>>
TEST.VALUE:Drv_SPI.NC_SPI_Write32.pBuf[0]:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Write32.Length:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].SER.Reg:1
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x10
TEST.END

-- Subprogram: NC_SPI_WriteDummy

-- Test Case: NC_SPI_WriteDummy.001
TEST.UNIT:Drv_SPI
TEST.SUBPROGRAM:NC_SPI_WriteDummy
TEST.NEW
TEST.NAME:NC_SPI_WriteDummy.001
TEST.STUB:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty
TEST.STUB:Drv_SPI.NC_SPI_WaitBusIsBusy
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI:<<malloc 1>>
TEST.VALUE:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x0
TEST.VALUE:Drv_SPI.NC_SPI_WaitTxFIFOIsEmpty.return:0
TEST.VALUE:Drv_SPI.NC_SPI_WaitBusIsBusy.return:0
TEST.VALUE:Drv_SPI.NC_SPI_WriteDummy.Length:1
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.EXPECTED:Drv_SPI.<<GLOBAL>>.RegA6_SPI[0].DRX.Reg:0x0
TEST.END

-- Unit: Svc_sFlash

-- Subprogram: NC_SF_DMA_QSPI_ReadData

-- Test Case: NC_SF_DMA_QSPI_ReadData.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_DMA_QSPI_ReadData
TEST.NEW
TEST.NAME:NC_SF_DMA_QSPI_ReadData.001
TEST.STUB:Drv_DMA330.NC_DMA_Start
TEST.STUB:Drv_DMA330.NC_DMA_Wait_Complete
TEST.STUB:Drv_DMA330.NC_DMA_Deinit
TEST.STUB:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Drv_SPI.NC_SPI_EnableDMAReq
TEST.STUB:Drv_SPI.NC_SPI_DisableDMAReq
TEST.STUB:Drv_SPI.NC_SPI_SetFrameSize
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.STUB:Drv_SPI.NC_SPI_SetDataLevel
TEST.STUB:Drv_SPI.NC_SPI_SetTransferLength
TEST.STUB:Drv_SPI.NC_QSPI_Write
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.pData[0]:0x0
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_QSPI_Gen_Instruction.Length:0x10001,0x1
TEST.VALUE:Drv_SPI.NC_SPI_SetFrameSize.Size:0x1F
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.VALUE:Drv_SPI.NC_SPI_SetDataLevel.Rx:16
TEST.VALUE:Drv_SPI.NC_SPI_SetTransferLength.Size:0x400,0x0
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[0]:0xEB
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[1]:0x20000000
TEST.VALUE:Drv_SPI.NC_QSPI_Write.Length:2
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.Addr:0x20000000
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[0]:0x0
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.Size:0x10001
TEST.ATTRIBUTES:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData[0]:INPUT_BASE=16
TEST.ATTRIBUTES:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.PageAddr:INPUT_BASE=16
TEST.ATTRIBUTES:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.Length:INPUT_BASE=16
TEST.ATTRIBUTES:Drv_SPI.NC_SPI_Write32.pBuf[0]:INPUT_BASE=16
TEST.ATTRIBUTES:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Addr:INPUT_BASE=16
TEST.ATTRIBUTES:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[0]:INPUT_BASE=16
TEST.ATTRIBUTES:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Size:INPUT_BASE=16
TEST.END

-- Subprogram: NC_SF_DMA_SPI_ReadData

-- Test Case: NC_SF_DMA_SPI_ReadData.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_DMA_SPI_ReadData
TEST.NEW
TEST.NAME:NC_SF_DMA_SPI_ReadData.001
TEST.STUB:Drv_DMA330.NC_DMA_Start
TEST.STUB:Drv_DMA330.NC_DMA_Wait_Complete
TEST.STUB:Drv_DMA330.NC_DMA_Deinit
TEST.STUB:Drv_DMA330.NC_DMA_SPI_Gen_Instruction
TEST.STUB:Drv_SPI.NC_SPI_Write32
TEST.STUB:Drv_SPI.NC_SPI_WriteDummy
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Drv_SPI.NC_SPI_EnableDMAReq
TEST.STUB:Drv_SPI.NC_SPI_DisableDMAReq
TEST.STUB:Drv_SPI.NC_SPI_SetFrameSize
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.STUB:Drv_SPI.NC_SPI_SetDataLevel
TEST.STUB:Drv_SPI.NC_SPI_SetTransferLength
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.pData[0]:0x0
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.PageAddr:0x20000000
TEST.VALUE:Drv_DMA330.NC_DMA_SPI_Gen_Instruction.Length:0x10001,0x1
TEST.VALUE:Drv_SPI.NC_SPI_Write32.pBuf[0]:0x23000000
TEST.VALUE:Drv_SPI.NC_SPI_Write32.Length:1
TEST.VALUE:Drv_SPI.NC_SPI_WriteDummy.Length:1
TEST.VALUE:Drv_SPI.NC_SPI_SetFrameSize.Size:0x1F
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.VALUE:Drv_SPI.NC_SPI_SetDataLevel.Rx:4
TEST.VALUE:Drv_SPI.NC_SPI_SetTransferLength.Size:0x4000,0x0
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Addr:0x20000000
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[0]:0x0
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Size:0x10001
TEST.ATTRIBUTES:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.Addr:INPUT_BASE=16
TEST.ATTRIBUTES:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[0]:INPUT_BASE=16
TEST.END

-- Subprogram: NC_SF_DeInit

-- Test Case: NC_SF_DeInit.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_DeInit
TEST.NEW
TEST.NAME:NC_SF_DeInit.001
TEST.STUB:Drv_SPI.NC_SPI_DeInit
TEST.END

-- Subprogram: NC_SF_EnableDeviceQuadMode

-- Test Case: NC_SF_EnableDeviceQuadMode.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableDeviceQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableDeviceQuadMode.001
TEST.STUB:Svc_sFlash.NC_SF_EnableQuadMode
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.Config:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableDeviceQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableDeviceQuadMode.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableDeviceQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableDeviceQuadMode.002
TEST.STUB:Svc_sFlash.NC_SF_EnableQuadMode_Type
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:1
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.Config:1
TEST.VALUE:Svc_sFlash.NC_SF_EnableDeviceQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableDeviceQuadMode.return:0
TEST.END

-- Subprogram: NC_SF_EnableQuadMode

-- Test Case: NC_SF_EnableQuadMode.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.001
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x2
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xEF
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xEF
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.002
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus2
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status1:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status2:0x3
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xEF
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xEF
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.003
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.003
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x40
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xC2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xC2
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.004
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.004
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus.Status:0x41
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xC2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xC2
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.005
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.005
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x2
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus.Status:0x41
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xC8
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xC8
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.006
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.006
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus3
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus3.Status:0x3
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xC8
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xC8
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.007
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.007
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus4
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0x1C
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0x1C
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.008
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.008
TEST.STUB:Svc_sFlash.NC_SF_ReadConfigStatus
TEST.STUB:Svc_sFlash.NC_SF_WriteConfigStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadConfigStatus.return:0x8
TEST.VALUE:Svc_sFlash.NC_SF_WriteConfigStatus.Status:0x68
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0x20
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0x20
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.009
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.009
TEST.STUB:Svc_sFlash.NC_SF_ReadConfigStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadConfigStatus.return:0x60
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0x20
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0x20
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode.010
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode.010
TEST.STUB:Svc_sFlash.NC_SF_ReadID
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0xFC
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.pRDID[0]:0xFC
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode.return:-1
TEST.END

-- Subprogram: NC_SF_EnableQuadMode_Type

-- Test Case: NC_SF_EnableQuadMode_Type.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.001
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus2
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status1:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status2:0x3
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:1
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.002
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:1
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.003
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.003
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus.Status:0x41
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.004
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.004
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x40
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.005
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.005
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x2
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:3
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.006
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.006
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus2
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus3
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0x1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus3.Status:0x3
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:3
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.007
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.007
TEST.STUB:Svc_sFlash.NC_SF_WriteStatus4
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:4
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.008
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.008
TEST.STUB:Svc_sFlash.NC_SF_ReadConfigStatus
TEST.VALUE:Svc_sFlash.NC_SF_ReadConfigStatus.return:0x60
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:5
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.009
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.009
TEST.STUB:Svc_sFlash.NC_SF_ReadConfigStatus
TEST.STUB:Svc_sFlash.NC_SF_WriteConfigStatus
TEST.VALUE:Svc_sFlash.NC_SF_ReadConfigStatus.return:0x8
TEST.VALUE:Svc_sFlash.NC_SF_WriteConfigStatus.Status:0x68
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:5
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.END

-- Test Case: NC_SF_EnableQuadMode_Type.010
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_EnableQuadMode_Type
TEST.NEW
TEST.NAME:NC_SF_EnableQuadMode_Type.010
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.Config:10
TEST.VALUE:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_EnableQuadMode_Type.return:-1
TEST.END

-- Subprogram: NC_SF_Init

-- Test Case: NC_SF_Init.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_Init
TEST.NEW
TEST.NAME:NC_SF_Init.001
TEST.STUB:Drv_SPI.NC_SPI_Init
TEST.END

-- Subprogram: NC_SF_QSPI_ReadData

-- Test Case: NC_SF_QSPI_ReadData.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_QSPI_ReadData
TEST.NEW
TEST.NAME:NC_SF_QSPI_ReadData.001
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.STUB:Drv_SPI.NC_QSPI_Read
TEST.STUB:Drv_SPI.NC_QSPI_Write
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.VALUE:Drv_SPI.NC_QSPI_Read.pBuf:0x20000000
TEST.VALUE:Drv_SPI.NC_QSPI_Read.Length:25
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[0]:0xEB
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[1]:0x20000000
TEST.VALUE:Drv_SPI.NC_QSPI_Write.Length:2
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Addr:0x20000000
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.pData:0x100
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Size:25
TEST.END

-- Test Case: NC_SF_QSPI_ReadData.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_QSPI_ReadData
TEST.NEW
TEST.NAME:NC_SF_QSPI_ReadData.002
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.STUB:Drv_SPI.NC_QSPI_Read
TEST.STUB:Drv_SPI.NC_QSPI_Write
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.VALUE:Drv_SPI.NC_QSPI_Read.pBuf:0x20000000
TEST.VALUE:Drv_SPI.NC_QSPI_Read.Length:256
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[0]:0xEB
TEST.VALUE:Drv_SPI.NC_QSPI_Write.pBuf[1]:0x20000000
TEST.VALUE:Drv_SPI.NC_QSPI_Write.Length:2
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Addr:0x20000000
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.pData:0x100
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Size:256
TEST.END

-- Subprogram: NC_SF_ReadConfigStatus

-- Test Case: NC_SF_ReadConfigStatus.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadConfigStatus
TEST.NEW
TEST.NAME:NC_SF_ReadConfigStatus.001
TEST.STUB:Drv_SPI.NC_SPI_Read
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[0]:0x65
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x85
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadConfigStatus.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadConfigStatus.return:0x65
TEST.END

-- Subprogram: NC_SF_ReadData

-- Test Case: NC_SF_ReadData.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadData
TEST.NEW
TEST.NAME:NC_SF_ReadData.001
TEST.STUB:Svc_sFlash.NC_SF_DMA_QSPI_ReadData
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[0]:1
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[1]:2
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[2]:3
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[3]:4
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[4]:5
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[5]:6
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[6]:7
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.pData[7]:8
TEST.VALUE:Svc_sFlash.NC_SF_DMA_QSPI_ReadData.Size:0x40
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.CtrlMode:4
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData:<<malloc 8>>
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[1]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[2]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[3]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[4]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[5]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[6]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[7]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Size:8
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[0]:1
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[1]:2
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[2]:3
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[3]:4
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[4]:5
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[5]:6
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[6]:7
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[7]:8
TEST.END

-- Test Case: NC_SF_ReadData.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadData
TEST.NEW
TEST.NAME:NC_SF_ReadData.002
TEST.STUB:Svc_sFlash.NC_SF_DMA_SPI_ReadData
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[0]:8
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[1]:7
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[2]:6
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[3]:5
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[4]:4
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[5]:3
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[6]:2
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.pData[7]:1
TEST.VALUE:Svc_sFlash.NC_SF_DMA_SPI_ReadData.Size:8
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.CtrlMode:3
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData:<<malloc 8>>
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[1]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[2]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[3]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[4]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[5]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[6]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[7]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Size:8
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[0]:8
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[1]:7
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[2]:6
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[3]:5
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[4]:4
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[5]:3
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[6]:2
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[7]:1
TEST.END

-- Test Case: NC_SF_ReadData.003
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadData
TEST.NEW
TEST.NAME:NC_SF_ReadData.003
TEST.STUB:Svc_sFlash.NC_SF_QSPI_ReadData
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.pData:0x100
TEST.VALUE:Svc_sFlash.NC_SF_QSPI_ReadData.Size:8
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.CtrlMode:2
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData:<<malloc 8>>
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[1]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[2]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[3]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[4]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[5]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[6]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[7]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Size:8
TEST.END

-- Test Case: NC_SF_ReadData.004
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadData
TEST.NEW
TEST.NAME:NC_SF_ReadData.004
TEST.STUB:Svc_sFlash.NC_SF_SPI_ReadData
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[0]:1
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[1]:2
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[2]:1
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[3]:2
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[4]:7
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[5]:8
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[6]:7
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[7]:8
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.Size:8
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.CtrlMode:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Addr:0x10000000
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData:<<malloc 8>>
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[1]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[2]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[3]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[4]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[5]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[6]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.pData[7]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadData.Size:8
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[0]:1
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[1]:2
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[2]:1
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[3]:2
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[4]:7
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[5]:8
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[6]:7
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadData.pData[7]:8
TEST.END

-- Subprogram: NC_SF_ReadID

-- Test Case: NC_SF_ReadID.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadID
TEST.NEW
TEST.NAME:NC_SF_ReadID.001
TEST.STUB:Drv_SPI.NC_SPI_Read
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[0]:0x11
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[1]:0x22
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[2]:0x33
TEST.VALUE:Drv_SPI.NC_SPI_Read.Length:3
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x9F
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff:<<malloc 3>>
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[1]:0
TEST.VALUE:Svc_sFlash.NC_SF_ReadID.pBuff[2]:0
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadID.pBuff[0]:0x11
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadID.pBuff[1]:0x22
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadID.pBuff[2]:0x33
TEST.ATTRIBUTES:Drv_SPI.NC_SPI_Read.pBuf[0]:EXPECTED_BASE=16
TEST.ATTRIBUTES:Drv_SPI.NC_SPI_Read.pBuf[1]:EXPECTED_BASE=16
TEST.ATTRIBUTES:Drv_SPI.NC_SPI_Read.pBuf[2]:EXPECTED_BASE=16
TEST.END

-- Subprogram: NC_SF_ReadStatus

-- Test Case: NC_SF_ReadStatus.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadStatus
TEST.NEW
TEST.NAME:NC_SF_ReadStatus.001
TEST.STUB:Drv_SPI.NC_SPI_Read
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[0]:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Read.Length:1
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadStatus.return:0x10
TEST.END

-- Subprogram: NC_SF_ReadStatus2

-- Test Case: NC_SF_ReadStatus2.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_ReadStatus2
TEST.NEW
TEST.NAME:NC_SF_ReadStatus2.001
TEST.STUB:Drv_SPI.NC_SPI_Read
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.VALUE:Drv_SPI.NC_SPI_Read.Length:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x35
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus2.return:0
TEST.EXPECTED:Svc_sFlash.NC_SF_ReadStatus2.return:0x0
TEST.END

-- Subprogram: NC_SF_SPI_ReadData

-- Test Case: NC_SF_SPI_ReadData.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_SPI_ReadData
TEST.NEW
TEST.NAME:NC_SF_SPI_ReadData.001
TEST.STUB:Drv_SPI.NC_SPI_Read
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Drv_SPI.NC_SPI_SetTMOD
TEST.VALUE:Drv_SPI.NC_SPI_Read.pBuf[0]:0x0
TEST.VALUE:Drv_SPI.NC_SPI_Read.Length:257
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x3
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[1]:0x80
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[2]:0x0
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[3]:0x0
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:4
TEST.VALUE:Drv_SPI.NC_SPI_SetTMOD.Mode:2
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.Addr:0x800000
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData:<<malloc 1>>
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.pData[0]:0x0
TEST.VALUE:Svc_sFlash.NC_SF_SPI_ReadData.Size:257
TEST.END

-- Subprogram: NC_SF_WriteConfigStatus

-- Test Case: NC_SF_WriteConfigStatus.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteConfigStatus
TEST.NEW
TEST.NAME:NC_SF_WriteConfigStatus.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_WriteEnable
TEST.STUB:Svc_sFlash.NC_SF_WriteDisable
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x81
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[1]:0x7
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:2
TEST.VALUE:Svc_sFlash.NC_SF_WriteConfigStatus.Status:0x7
TEST.END

-- Subprogram: NC_SF_WriteDisable

-- Test Case: NC_SF_WriteDisable.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteDisable
TEST.NEW
TEST.NAME:NC_SF_WriteDisable.001
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:1
TEST.END

-- Test Case: NC_SF_WriteDisable.002
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteDisable
TEST.NEW
TEST.NAME:NC_SF_WriteDisable.002
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:1000
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf:"4"
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:1,0
TEST.END

-- Subprogram: NC_SF_WriteEnable

-- Test Case: NC_SF_WriteEnable.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteEnable
TEST.NEW
TEST.NAME:NC_SF_WriteEnable.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_ReadStatus
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.mSec:500
TEST.VALUE:uut_prototype_stubs.NC_SCU_mTimeOut.return:0,1
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x6
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_ReadStatus.return:0x1
TEST.END

-- Subprogram: NC_SF_WriteStatus

-- Test Case: NC_SF_WriteStatus.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteStatus
TEST.NEW
TEST.NAME:NC_SF_WriteStatus.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_WriteEnable
TEST.STUB:Svc_sFlash.NC_SF_WriteDisable
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x1
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[1]:0x7
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus.Status:0x7
TEST.END

-- Subprogram: NC_SF_WriteStatus2

-- Test Case: NC_SF_WriteStatus2.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteStatus2
TEST.NEW
TEST.NAME:NC_SF_WriteStatus2.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_WriteEnable
TEST.STUB:Svc_sFlash.NC_SF_WriteDisable
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x1
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[1]:0x7
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[2]:0x15
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:3
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status1:0x7
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus2.Status2:0x15
TEST.END

-- Subprogram: NC_SF_WriteStatus3

-- Test Case: NC_SF_WriteStatus3.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteStatus3
TEST.NEW
TEST.NAME:NC_SF_WriteStatus3.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_WriteEnable
TEST.STUB:Svc_sFlash.NC_SF_WriteDisable
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x31
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[1]:0x10
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:2
TEST.VALUE:Svc_sFlash.NC_SF_WriteStatus3.Status:0x10
TEST.END

-- Subprogram: NC_SF_WriteStatus4

-- Test Case: NC_SF_WriteStatus4.001
TEST.UNIT:Svc_sFlash
TEST.SUBPROGRAM:NC_SF_WriteStatus4
TEST.NEW
TEST.NAME:NC_SF_WriteStatus4.001
TEST.STUB:Drv_SPI.NC_SPI_Write
TEST.STUB:Drv_SPI.NC_SPI_EnableCS
TEST.STUB:Drv_SPI.NC_SPI_DisableCS
TEST.STUB:Svc_sFlash.NC_SF_WriteEnable
TEST.STUB:Svc_sFlash.NC_SF_WriteDisable
TEST.VALUE:Drv_SPI.NC_SPI_Write.pBuf[0]:0x38
TEST.VALUE:Drv_SPI.NC_SPI_Write.Length:1
TEST.END
