-- VectorCAST 19.sp2 (09/10/19)
-- Test Case Script
-- 
-- Environment    : APACHE6_BL1_UNIT_MPU
-- Unit(s) Under Test: MPU
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Subprogram: NC_MPU_EnableDebugRegion

-- Test Case: NC_MPU_EnableDebugRegion.001
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_EnableDebugRegion
TEST.NEW
TEST.NAME:NC_MPU_EnableDebugRegion.001
TEST.STUB:MPU.NC_MPU_SetRegion
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x20000000,0x30000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:2,3
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.RegionType:2,3
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.return:0x20000000,0x30000000
TEST.END

-- Subprogram: NC_MPU_EnterSafetyGate

-- Test Case: NC_MPU_EnterSafetyGate.001
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_EnterSafetyGate
TEST.NEW
TEST.NAME:NC_MPU_EnterSafetyGate.001
TEST.STUB:MPU.NC_MPU_SetRegion
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG16.Reg:0
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:1
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.RegionType:1
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.return:0x10000000
TEST.EXPECTED:MPU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG16.Reg:1
TEST.END

-- Subprogram: NC_MPU_LeaveSafetyGate

-- Test Case: NC_MPU_LeaveSafetyGate.001
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_LeaveSafetyGate
TEST.NEW
TEST.NAME:NC_MPU_LeaveSafetyGate.001
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG16.Reg:2
TEST.EXPECTED:MPU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG16.Reg:1
TEST.END

-- Test Case: NC_MPU_LeaveSafetyGate.002
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_LeaveSafetyGate
TEST.NEW
TEST.NAME:NC_MPU_LeaveSafetyGate.002
TEST.STUB:MPU.NC_MPU_SetRegion
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU:<<malloc 1>>
TEST.VALUE:MPU.<<GLOBAL>>.RegA6_CPU_SCU[0].CPU_SCU_DEBUG16.Reg:0
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0xB
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:1
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.RegionType:1
TEST.VALUE:uut_prototype_stubs.NC_MPU_GET_REGION_AREA.return:0x10000000
TEST.END

-- Subprogram: NC_MPU_SetRegion

-- Test Case: NC_MPU_SetRegion.001
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_SetRegion
TEST.NEW
TEST.NAME:NC_MPU_SetRegion.001
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:1
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_SAFETY_ENGINE_TXT.Region:0x10000000
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_SAFETY_ENGINE_TXT.Attr:0x30B
TEST.END

-- Test Case: NC_MPU_SetRegion.002
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_SetRegion
TEST.NEW
TEST.NAME:NC_MPU_SetRegion.002
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:2
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_DEBUG_SECTION.Region:0x10000000
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_DEBUG_SECTION.Attr:0x30B
TEST.END

-- Test Case: NC_MPU_SetRegion.003
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_SetRegion
TEST.NEW
TEST.NAME:NC_MPU_SetRegion.003
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:3
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_DEBUG_DATA_SECTION.Region:0x10000000
TEST.VALUE:uut_prototype_stubs.NC_MPU_SET_REGION_DEBUG_DATA_SECTION.Attr:0x30B
TEST.END

-- Test Case: NC_MPU_SetRegion.004
TEST.UNIT:MPU
TEST.SUBPROGRAM:NC_MPU_SetRegion
TEST.NEW
TEST.NAME:NC_MPU_SetRegion.004
TEST.VALUE:MPU.NC_MPU_SetRegion.Region:0x10000000
TEST.VALUE:MPU.NC_MPU_SetRegion.Attr:0x30B
TEST.VALUE:MPU.NC_MPU_SetRegion.RegionType:4
TEST.END
