/* This file is automatically generated by the Makefile! [ "2025/09/17" "12:15:35" ]  */
#ifndef GENCONFIG_H_
#define GENCONFIG_H_

#ifndef FPGA_DB_CLOCK 
#define FPGA_DB_CLOCK 40000
#endif

#ifndef EVT 
#define EVT 0
#endif

#ifndef BL1_
#define BL1_
#endif

#ifndef BL_SEL 
#define BL_SEL 1
#endif

#ifndef USB_DLOAD_
#define USB_DLOAD_
#endif

#ifndef EST_MODE_
#define EST_MODE_
#endif

#ifndef SECURE_BOOT_
#define SECURE_BOOT_
#endif

#ifndef OTP_ENABLE_
#define OTP_ENABLE_
#endif

#ifndef CMRT_ENABLE_
#define CMRT_ENABLE_
#endif

#ifndef DFORCE_CMRT_OTP_CONFIG_
#define DFORCE_CMRT_OTP_CONFIG_
#endif

#ifndef BL_VER_MAJOR 
#define BL_VER_MAJOR 1
#endif

#ifndef BL_VER_MINOR 
#define BL_VER_MINOR 0
#endif

#ifndef BL_VER_PATCH 
#define BL_VER_PATCH 5
#endif

#endif
